### ISSUE TITLE
App crashed at the start

### ISSUE THREAD

**Issue by 9to1url** [jpochyla/psst#1]
@**Jan Pochyla** , I am checking  your code, also applied Spotify account, but after setting .env , get this error:
```
[2020-08-21T21:08:49Z ERROR rspotify::blocking::oauth2] couldn't open .spotify_token_cache.json: "No such file or directory (os error 2)"
```

ALso after enter the redirect URL, I got this.
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/database.rs:242:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any idea?

**Comment by jpochyla** [comment]
Thanks for the report! This part of the code has been severely rewritten since then, and now needs just the device credentials from the Spotify Account Settings, as rescribed in the README.
