### ISSUE TITLE
Running without opening the terminal window

### ISSUE THREAD

**Issue by sintezcs** [jpochyla/psst#106]
Hi guys, thank you for a great product! I have a question, is it possible to not show the terminal window when running an app in Mac OS?

**Comment by timgws** [comment]
Yeah, it's definitely possible. I think we will need to build an app bundle, though.

https://github.com/burtonageo/cargo-bundle, https://developer.apple.com/go/?id=bundle-structure

**Comment by sintezcs** [comment]
@timgws cool, thank you! I'll try this out

**Comment by jpochyla** [comment]
Closing as duplicate of #82, it's in the works :)
