### ISSUE TITLE
[GUI] Hovered item not correctly highlighted after scrolling down.

### ISSUE THREAD

**Issue by Enellis** [jpochyla/psst#11]
System: macOS 10.15.17

In the song select list its flickering really fast (not visible in the gif) and in the playlist view on the left sidebar it is highlighting the wrong playlist after scrolling down. After scrolling all the way up it is working normally again.

![](https://s2.gifyu.com/images/ezgif.com-video-to-gifca11f7046e04f5b7.gif)

**Comment by jpochyla** [comment]
Thanks for the report! There is a PR with a fix pending in the Druid repo: https://github.com/linebender/druid/pull/1475

**Comment by Enellis** [comment]
Sure, I'm glad to help. I saw the PR got merged and I tried it again. Unfortunately the issue still persists and seems to be correlated with linebender/druid#1507.

**Comment by jpochyla** [comment]
Thanks!
