### ISSUE TITLE
Logo/icon needed!

### ISSUE THREAD

**Issue by jpochyla** [jpochyla/psst#110]
Hi! We definitely need a proper application icon, ideally with a logotype (the muted-mic logo is a bit of a placeholder). Unfortunately I'm useless with graphics, so I'm looking for help.

Ideas/inspiration:

- I like the [typical macOS icons](https://www.macosicongallery.com).
- Where I'm from, "psst" is a "shh", "be quiet" sound. So maybe the classical "finger on lips", simplified?
- Some play on the Spotify logo? Without copying the exact shape of course, and without the green.
- I tried [goofing around with Processing and Joy Division-style soundwaves](https://user-images.githubusercontent.com/1055497/129920734-f41a8d45-181f-4468-b699-6e4c0c9a902e.png), but it doesn't look that well in small sizes. Also the silver rect is too generic on Mac.

Thanks!

**Comment by Qrbaker** [comment]
@jpochyla I'll look into this. Do you have a preference for the image artifact? I'll probably work on it in inkscape so I can give you .svg, .png, and .ico

**Comment by jpochyla** [comment]
> I can give you .svg, .png, and .ico.

Yep these sound great, I think `.svg` would be the most important.

**Comment by Qrbaker** [comment]
![psst](https://user-images.githubusercontent.com/14336407/130040236-a2170e04-33c0-44d7-ac8c-7187a6ea7d4b.png)

Here's a first go, trying to convey the "psst/shush finger on lips idea". Feedback welcome.

**Comment by phildenhoff** [comment]
@Qrbaker I like your logo! I tried it out but I found the lips become pretty hard to see on my dock with ~30 items so it's essentially just the shush hand. Honestly I think you could just go with that :)

![image](https://user-images.githubusercontent.com/17505728/130127867-671cd159-8abc-4bec-b61b-116a7c094bd2.png)

**Comment by Qrbaker** [comment]
@phildenhoff thanks for the test.

I'll experiment with making the mouth lines thicker and brighter to see if that looks any better

**Comment by Kethku** [comment]
I wonder if just removing the lips would be better. The finger alone may be enough

**Comment by Qrbaker** [comment]
![psst](https://user-images.githubusercontent.com/14336407/130161959-8346eaea-e524-4c30-9a09-d834854cbd53.png)
![psst_no_mouth](https://user-images.githubusercontent.com/14336407/130161989-26641bde-3e8b-4d45-8708-d5f0c66a8e2e.png)

Here's too more versions: the top, with a thicker stroke on the mouth + primary color, and a second with no mouth.

**Comment by jpochyla** [comment]
Oooh, thanks a lot @Qrbaker! I like this direction a lot. Could we try different colours, like orange, blue, or some others? I'm not sure about the green (esp. in combination with the black background, it's a bit Matrix-y) :| If you send over the SVG I can try experiment with colors myself.

**Comment by Qrbaker** [comment]
@jpochyla https://gist.github.com/Qrbaker/f956a303350f061fedfca263584f0f5b Here you go :)

**Comment by JustinAiken** [comment]
> Here's too more versions: the top, with a thicker stroke on the mouth + primary color, and a second with no mouth.

It would be cool if one of those was the icons when it was playing vs when it's paused

**Comment by Qrbaker** [comment]
> It would be cool if one of those was the icons when it was playing vs when it's paused

It would be cool, but I don't know if Druid supports anything like that.

**Comment by pablodz** [comment]
Looks great the green one, also maybe a UX/UI cool and modern design would be perfect. Like transparent background or dynamic background according to the song

**Comment by mradke** [comment]
@jpochyla could you elaborate on _why_ the application is named `psst`?

E. g. "I'm listening to music, so I don't have to hear my co workers make noise" or something along those lines. I'd imagine that it could be useful to come up with some other ideas for logos outside of the ones already presented.

**Comment by yavko** [comment]
@danielgolden I made something similar to Ur idea like a month ago and completely forgot about it, I didn't use anyone's work I made the face and hand by hand and the font is SF COMPACT Rounded (not 100% its the compact version) SF is the macOS and iOS built in font BTW.


<details>
<summary>The icon I made</summary>

![psst](https://user-images.githubusercontent.com/15178513/136109555-83197093-a061-4d13-9fea-91b2f18464ba.png)
</details>

<details>
<summary>ur message</summary>

[**@Daniel Golden**](https://github.com/danielgolden) commented on [Aug 27, 2021, 6:10 AM PDT](https://github.com/jpochyla/psst/issues/110#issuecomment-907191189 "2021-08-27T13:10:11Z - Replied by Github Reply Comments"):
> Maybe a side profile of the "shh" could help make it more clear ([example](https://thenounproject.com/search/?q=shh&i=21041))?
> 
> [![Captura de Pantalla 2021-08-27 a la(s) 9 09 31 a  m](https://user-images.githubusercontent.com/812989/131132306-58d92aea-05b5-4339-8b99-c651dbfdc0ff.png)](https://user-images.githubusercontent.com/812989/131132306-58d92aea-05b5-4339-8b99-c651dbfdc0ff.png)



</details>

**Comment by Qrbaker** [comment]
It's a good start but have you tried it at a small size? When I scaled it down the lines become hard to tell apart and the text is unreadable.

I would try ditching the text and making the lines thicker.

On October 5, 2021 6:12:56 PM EDT, Yavor Kolev ***@***.***> wrote:
***@***.*** I made something similar to Ur idea like a month ago and completely forgot about it, I didn't use anyone's work I made the face and hand by hand and the font is SF COMPACT Rounded (not 100% its the compact version) SF is the macOS and iOS built in font BTW.
>
>
><details>
><summary>The icon I made</summary>
>
>![psst](https://user-images.githubusercontent.com/15178513/136109555-83197093-a061-4d13-9fea-91b2f18464ba.png)
></details>
>
><details>
><summary>ur message</summary>
>
***@***.*** Golden**](https://github.com/danielgolden) commented on [Aug 27, 2021, 6:10 AM PDT](https://github.com/jpochyla/psst/issues/110#issuecomment-907191189 "2021-08-27T13:10:11Z - Replied by Github Reply Comments"):

**Comment by shiftgeist** [comment]
![icon@64w](https://user-images.githubusercontent.com/30648730/136658672-d65ef7f8-6c9a-4864-a2c8-b2f4555e0409.png)
![icon@150w](https://user-images.githubusercontent.com/30648730/136658673-32079cda-f346-4274-befc-95b664f8ded4.png)

i gave it a shot, but am not quite happy with the result. It's all a bit too dark for my taste

about the concept: I tried to combine the library "psst" with sound waves which give the connection to music

**Comment by Qrbaker** [comment]
> 
> 
> ![icon@64w](https://user-images.githubusercontent.com/30648730/136658672-d65ef7f8-6c9a-4864-a2c8-b2f4555e0409.png) ![icon@150w](https://user-images.githubusercontent.com/30648730/136658673-32079cda-f346-4274-befc-95b664f8ded4.png)
> 
> i gave it a shot, but am not quite happy with the result. It's all a bit too dark for my taste
> 
> about the concept: I took the example from @danielgolden and tried to combine the library "psst" with sound waves which give the connection to music

Oooh that looks great!

**Comment by jpochyla** [comment]
@Qrbaker I'm sorry for being such a slowpoke, I've took the shape from your design and tried to add a bunch of stuff around, and I'd like to use this :) Is that OK?
![logo_512](https://user-images.githubusercontent.com/1055497/144388877-5068e41b-783d-4d1f-a75f-bd843bc39491.png)

**Comment by yavko** [comment]
> @Qrbaker I'm sorry for being such a slowpoke, I took the shape from your design and tried to add a bunch of stuff around, and I'd like to use this :) Is that OK? ![logo_512](https://user-images.githubusercontent.com/1055497/144388877-5068e41b-783d-4d1f-a75f-bd843bc39491.png)

ooh

**Comment by Qrbaker** [comment]
> @Qrbaker I'm sorry for being such a slowpoke, I took the shape from your design and tried to add a bunch of stuff around, and I'd like to use this :) Is that OK? ![logo_512](https://user-images.githubusercontent.com/1055497/144388877-5068e41b-783d-4d1f-a75f-bd843bc39491.png)

Absolutely! I used assets that were public domain and I'm quite happy to give the work to the project under the license it uses.

I think you did a great job with it!

**Comment by shiftgeist** [comment]
> ![logo_512](https://user-images.githubusercontent.com/1055497/144388877-5068e41b-783d-4d1f-a75f-bd843bc39491.png)

This looks sooo good! Amazing job

one small mimimi: the distinguishment between these two lines is hard to make out 
![image](https://user-images.githubusercontent.com/30648730/144461957-5237b241-2b50-42cd-80e4-f9cecaf2a570.png)

**Comment by jacksongoode** [comment]
@Qrbaker Just wondering if it might be possible to make a pure SVG (non-rasterized version of just the hand?) I was thinking of replacing the mute icon in the top left with this.

<img width="476" alt="Screen Shot 2023-05-10 at 1 39 26 PM" src="https://github.com/jpochyla/psst/assets/54308792/56201979-e4de-464f-8f5f-09538eb3b111">

**Comment by Qrbaker** [comment]
@jpochyla has since modified it a fair bit and likely has the most up to date version.

Here’s the SVG I had last tinkered with, you should be able to take what you need from there using Inkscape or Illustrator:

https://gist.github.com/Qrbaker/f956a303350f061fedfca263584f0f5b

> @Qrbaker Just wondering if it might be possible to make a pure SVG (non-rasterized version of just the hand?) I was thinking of replacing the mute icon in the top left with this.
> 
> <img alt="Screen Shot 2023-05-10 at 1 39 26 PM" width="476" src="https://user-images.githubusercontent.com/54308792/237510107-56201979-e4de-464f-8f5f-09538eb3b111.png">

**Comment by jpochyla** [comment]
Hi! I used Affinity Designer to edit the icon, I believe there's a project file for it in the repo.
