### ISSUE TITLE
Albums view throws error

### ISSUE THREAD

**Issue by panmau** [jpochyla/psst#112]
When I go to the Albums page I get the following error:
`Failed to read JSON: invalid type: null, expected a string at line 18201 column 20`

Environment: Manjaro Linux 21.1.0

**Comment by jpochyla** [comment]
Which artist is it?

**Comment by joelarmstrong** [comment]
I have the same issue, or a similar one (loading the "Albums" tab on the sidebar). The offending album (Electric Wizard - Come My Fanatics) has a null label:

```
          [snip]
          "is_playable" : true,
          "label" : null,
          "name" : "Come My Fanatics",
          "popularity" : 0,
          "release_date" : "2008-08-05",
          "release_date_precision" : "day",
          "total_tracks" : 8,
          [snip]
```

After creating a custom deserializer that handles null `label`s (instead of just a *missing* `label`) the tab loads fine.

**Comment by panmau** [comment]
> Which artist is it?

Sorry I meant to write Albums page.

**Comment by jpochyla** [comment]
Uff, thanks! Spotify API can be a bit weird sometimes (seems like label is not even documented anymore). Can you please confirm eb7384a fixes the issue? Thanks!

**Comment by panmau** [comment]
@jpochyla Yes that fixes the issue for me.
