### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by Bios-Marcel** [jpochyla/psst#114]
OS: Ubuntu 20.04 amd64
Rust: rustc 1.49.0 (e1884a8e3 2020-12-29)
Commit: 967c077

Output:
```
marcel@marcel-desktop:/mnt/data/code/psst$ git submodule update --recursive --init
marcel@marcel-desktop:/mnt/data/code/psst$ cargo build --release
warning: /mnt/data/code/psst/Cargo.toml: unused manifest key: profile.dev.split-debuginfo
   Compiling serde v1.0.127
   Compiling thiserror v1.0.26
   Compiling futures-util v0.3.16
   Compiling time-macros v0.1.1
   Compiling tracing v0.1.26
   Compiling souvlaki v0.4.1
error: unexpected token: `include_str`
 --> /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/souvlaki-0.4.1/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `souvlaki`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Am I missing something? This is the same commit as the one in the CI, so it should work, right?

**Comment by stared** [comment]
I have the same error (for `rustc 1.53.0  (53cb7b09b 2021-06-17)`) after running `cargo build`.

**Comment by jpochyla** [comment]
Latest Rust stable is needed.

**Comment by rklasen** [comment]
I've had the same issue, updating rust with `rustup update` fixed it.

**Comment by Bios-Marcel** [comment]
The compiler error is just pretty user unfriendly :)

**Comment by stared** [comment]
I updated that, and it works!
@jpochyla - you were right and by lastest, you really mean lastest, not almost that

* rustc 1.54.0 (a178d0322 2021-07-26) works
* rustc 1.53.0 (53cb7b09b 2021-06-17) does not work
