### ISSUE TITLE
Specific Playlist throws JSON error

### ISSUE THREAD

**Issue by panmau** [jpochyla/psst#115]
One of my playlists throws the following error when I try to open it: 
`Failed to read JSON: invalid type: null, expected a string at line 23 column 19`

The playlist is this one: https://open.spotify.com/playlist/35RLOEH1zKsTllJFwL9wvW

This seems like a similar issue as #112 

Thanks for taking a look!

**Comment by jpochyla** [comment]
Should be fixed in bbca2bc (master), can you please confirm? Local tracks are skipped completely and playlist URL pasting should be fixed as well.

**Comment by panmau** [comment]
Yes that fixes this error for me. Thanks for the fix.
