### ISSUE TITLE
macOS prebuilt binary doesn't work

### ISSUE THREAD

**Issue by vordenken** [jpochyla/psst#116]
Downloading the "psst-gui-macOS.zip" on your linked page (https://nightly.link/jpochyla/psst/workflows/build/master) downloads a file without suffix. Manually adding the .app suffix doesn't work either. 
Am I doing something wrong here?

**Comment by jpochyla** [comment]
It doesn't have +x permissions, but automatic macOS .app bundles should be ready soon.

**Comment by vordenken** [comment]
Thanks for your reply, a quick `sudo chmod +x psst-gui` fixed it. 
Looking forward to .app bundles!
