### ISSUE TITLE
Cant find a way to delete a track from a Playlist

### ISSUE THREAD

**Issue by pythonhacker** [jpochyla/psst#119]
![image](https://user-images.githubusercontent.com/316177/130080090-92ae16e6-d529-4613-9dfe-2b387cce112b.png)

**Comment by jpochyla** [comment]
Playlist management is currently not implemented, but definitely planned.

**Comment by Insprill** [comment]
Implemented in eb7192e978b5b16c43a41072e2f749d3745aa8d2.
