### ISSUE TITLE
Change One Line of Code to Support Free Accounts

### ISSUE THREAD

**Issue by chris124567** [jpochyla/psst#122]
`psst` does not currently support free accounts by default.  This can be easily fixed by switching `PRODUCT_PARTNER` to `PRODUCT_CLIENT` at https://github.com/jpochyla/psst/blob/0827aaa5c3ce87b4eef672d436fc363388ea5e36/psst-core/src/connection/mod.rs#L290 and selecting low or normal audio qualities.  Proof (I'm a free user): https://i.imgur.com/aSKXjgX.png.  I can understand why you may not want to do this (DMCA?) but I am just letting you know that this is an option.

**Comment by WaitroseDev** [comment]
I believe this was done as Psst doesn't support the free account skip limit?

**Comment by chris124567** [comment]
> I believe this was done as Psst doesn't support the free account skip limit?

From what I can tell, the "skip limit" does not actually exist server side and is only enforced clientside

**Comment by WaitroseDev** [comment]
> > I believe this was done as Psst doesn't support the free account skip limit?
> 
> From what I can tell, the "skip limit" does not actually exist server-side and is only enforced clientside

Not enforcing it would make psst break Spotify TOS off the top of my head, so it wouldn't be something that should be added, in my opinion. 

Furthermore, there are differences, such as Spotify Premium having higher audio quality and no adverts, whereas the Free plan enforces ads, etc.

If psst was to add support for these things, it would most likely be trivial for someone to remove them, which puts an unnecessary target on this project.

**Comment by jpochyla** [comment]
As I try to play by the Spotify rules as much as possible, I don't intend to support free accounts in Psst, but thank you for letting me know.
