### ISSUE TITLE
Playlists seem to get truncated

### ISSUE THREAD

**Issue by aw1cks** [jpochyla/psst#125]
Really liking the client so far! Love the minimalistic look.

Biggest issue I found so far, is that playlists seem to get truncated. My saved tracks playlist is over 1000 songs and only a few hundred seem to get shown.

**Comment by jpochyla** [comment]
Glad you like it! <3

Unfortunately only 200 tracks are loaded from each playlist, we already have #18 open for this. Closing as duplicate, but definitely in the queue!
