### ISSUE TITLE
Add UI for incorrect credentials?

### ISSUE THREAD

**Issue by jasikpark** [jpochyla/psst#13]
Currently there is logging for incorrect credentials, but there is no way to see in the interface that the credentials have been saved, updated, are incorrect, or are already saved and won't be replaced since they are the same.

<img width="1792" alt="Screen Shot 2021-01-04 at 5 02 40 PM" src="https://user-images.githubusercontent.com/10626596/103588483-e5b43280-4eae-11eb-841d-74105dae0e26.png">

**Comment by jasikpark** [comment]
I keep getting "already configured" when trying to update my credentials

**Comment by jasikpark** [comment]
Hmmmm ok so the logging is just simply not very clear, rather than the application being wrong, since I tried to clear my credentials and save and when I checked the config.json in application support, the credentials were cleared.

**Comment by jpochyla** [comment]
So I think the strategy here would be to try to connect in the config dialog itself, and show the error there. What is problematic in the current codebase is "restarting" already running session with different credentials, and that's what these "already configured" errors mean. It should work if you restart the app, although I agree it's not ideal.

**Comment by OpenUAS** [comment]
+1 for this change welcomed. The good thing is, pssst compiles and runs well on Ubuntu 20.04, now only if I would have a Spotify account ;) Tried it since this is good example for a rust app with Druid GUI.

**Comment by brightly-salty** [comment]
I think it would also be useful to include a string representation of the error. `AuthFailed { 11 }` is the error I got, but it took digging through keyexchange.proto to find that this meant "Premium account required".

**Comment by jpochyla** [comment]
Credential dialog is a bit nicer now, closing. Feel free to open issues in case of any problems!
