### ISSUE TITLE
Pre-built Windows binary flagged as a trojan by Windows Defender

### ISSUE THREAD

**Issue by jarmo** [jpochyla/psst#130]
I downloaded https://nightly.link/jpochyla/psst/workflows/build/master/Psst.exe.zip and couldn't extract it on my Windows 10 Pro since Windows Defender detected it being as a trojan (Trojan:Script/Wacatac.B!ml).

Any ideas why this is being detected as a threat?

**Comment by jpochyla** [comment]
No idea at all! Does Defender also flag it if you build it yourself?

**Comment by jarmo** [comment]
I don't know since I'm not familiar with Rust and its toolchain. I submitted it to [virustotal.com](https://www.virustotal.com/gui/file/99ef191eaa5082d486a2df49bed807a56507775465aaeb64bb81795225e9ae82/detection) where it was not flagged by anything. I'll guess it was a false alarm for some reason.

I'm closing this issue for now.
