### ISSUE TITLE
Track list items hover when the cursor is over the player controls

### ISSUE THREAD

**Issue by danfabi** [jpochyla/psst#131]
Items in the track list behind the player controls hover despite the cursor being only over the player controls.

https://user-images.githubusercontent.com/42783895/130267885-c73aa769-0e38-4b45-969d-fb233832d022.mp4

**Comment by jpochyla** [comment]
Yup, this is a bug in the upstream `Scroll` component.

**Comment by Insprill** [comment]
This appears to have been fixed by `linebender/druid#2149`.
