### ISSUE TITLE
Networking broken on Tumbleweed - Login not possible

### ISSUE THREAD

**Issue by Ozymandias42** [jpochyla/psst#133]
When compiled in and run in a 'Toolbox' Ubuntu container it works though without being able to see or connect to my audio. 
(I'm using pipewire)

When compiled natively on Tumbleweed or when starting the container-compiled version natively, the connection to the pipewire socket works but the following error occurs.

`[2021-08-21T12:02:22Z ERROR psst_core::connection] using AP fallback, error while resolving: AudioFetchingError(Transport(Transport { kind: Dns, message: None, url: Some(Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("apresolve.spotify.com")), port: None, path: "/", query: None, fragment: None }), source: Some(Custom { kind: Uncategorized, error: "failed to lookup address information: Name or service not known" }), response: None }))
`

**Comment by jpochyla** [comment]
Marking as wonfix, as it's something I personally won't work on. PRs welcome of course.
