### ISSUE TITLE
Lack of sound output using Pipewire (fedora 34)

### ISSUE THREAD

**Issue by cttipton** [jpochyla/psst#138]
Initially I built in an Ubuntu 20.04 VM on my fedora workstation, gave the VM access to my sound card via virt-manager, works like a charm.  On my actual machine using fedora 34 with pipewire (including pipewire-alsa module, pipewire-pulse service), I don't have any playback from the application--audio playback elsewhere the issue isn't observed.

I'll continue interrogating the alsa api -> pipewire routing and my configuration, but if any others are using pipewire (or can test it) contrary reports would be helpful in narrowing the scope of investigation.

There's nothing notable in the runtime logs which differentiates the two cases

[2021-08-23T05:16:58Z INFO  psst_core::access_token] access token expired, requesting
[2021-08-23T05:17:01Z INFO  psst_core::access_token] access token expired, requesting
[2021-08-23T05:17:01Z INFO  psst_core::audio_file] blocked at 10295584
[2021-08-23T05:17:01Z INFO  psst_core::audio_file] blocked at 10354686
[2021-08-23T05:17:01Z INFO  psst_core::audio_file] blocked at 10357428
[2021-08-23T05:17:01Z INFO  psst_core::audio_player] starting playback
[2021-08-23T05:17:01Z INFO  psst_gui::controller::playback] playing
[2021-08-23T05:17:04Z INFO  psst_core::audio_file] blocked at 2644028
[2021-08-23T05:17:04Z INFO  psst_core::audio_file] blocked at 2665709
[2021-08-23T05:17:04Z INFO  psst_core::audio_file] blocked at 2682093
[2021-08-23T05:17:04Z INFO  psst_core::audio_file] blocked at 2698477
[2021-08-23T05:17:04Z INFO  psst_core::audio_file] blocked at 2722297
[2021-08-23T05:17:37Z INFO  psst_core::audio_player] pausing playback

I will test enabling and forcing pipewire in my VM and report back.

**Comment by zrthxn** [comment]
I was also having some playback issues on my F34 machine. Did you build for fedora separately or did the same binary work on both? I seem to have completely different logs...

**Comment by mforsb** [comment]
I'm also on fedora 34 with pipewire 0.3.33 and am having a similar issue. Sometimes when playing a track psst does not play any sound, but I can see the volume bar moving in `pavucontrol`. Pausing and playing fixes it. 

When it works there is also some occasional crackling, especially when doing something cpu-intensive like compiling. This is also present (although much less noticeable) in [this](https://github.com/ExPixel/miniaudio-rs/blob/master/miniaudio/examples/simple-playback-decoder.rs) `miniaudio-rs` example (I changed it to play song instead). The crackling is accompanied by these messages in `journald`:
```
Aug 23 18:16:05 pipewire-pulse[1657]: 1 events suppressed
Aug 23 18:16:07 pipewire-pulse[1657]: 1 events suppressed
Aug 23 18:17:17 pipewire-pulse[1657]: 2 events suppressed
Aug 23 18:18:48 pipewire-pulse[1657]: 6 events suppressed
```

None of these issues appear with psst on pulseaudio, or with any other program on pipewire.

**Comment by cttipton** [comment]
My initial issue (lack of playback) appears to have been a problem with my pipewire setup.  Running defaults brought me to observe the same as @mforsb.  However, at least for the crackling/skipping I believe this to be a current pipewire flaw, as noted in https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/494 as well as [this issue](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/535) which also references use of miniaudio.

**Comment by jacksongoode** [comment]
@cttipton @mforsb did you find any current workaround for playback? I tried starting with `pw-jack` to no avail.

**Comment by mforsb** [comment]
Unfortunately no. But if you're able to build from source I have been trying out  [this](https://github.com/H-M-H/psst/tree/cpal) `cpal` based branch by @H-M-H for about an hour without any issues.

**Comment by jacksongoode** [comment]
> Unfortunately no. But if you're able to build from source I have been trying out [this](https://github.com/H-M-H/psst/tree/cpal) `cpal` based branch by @H-M-H for about an hour without any issues.

Did you start with any flags? I build it and it seems to exhibit the same behavior :(

**Comment by H-M-H** [comment]
Did you build the `cpal` branch?

**Comment by jacksongoode** [comment]
> Did you build the `cpal` branch?

I was running the wrong `psst-gui` from cargo :laughing:. It works well! I've brought it to the attention of the dev as well.
