### ISSUE TITLE
Include `psst.desktop` file in Linux installer

### ISSUE THREAD

**Issue by flotwig** [jpochyla/psst#144]
Include a `.desktop` file so that Linux users can search for the application, see the icon (once there's an icon), etc. 

Install a file like the following:

```
[Desktop Entry]
Name=Psst
Exec=/usr/bin/psst-gui
Icon=...
Type=Application
```

In `/usr/share/applications` or `~/.local/share/applications` if a local install.

`.desktop` entry spec: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by jpochyla** [comment]
We have a .desktop included in the .deb, is something wrong with it?

**Comment by DanySpin97** [comment]
`.deb` represents only a small fraction of all the Linux distributions and UNIX systems. On all other systems there should be a build system/installation script.

`cargo install` doesn't install files outside the build process, like `psst.desktop`. The most used program for installation is `make`. However, `Makefiles` are really hard to get right and they never support user-wide installation, as proposed by @flotwig.

There are two additional systems developed exactly for projects like psst: [rinstall](https://github.com/danyspin97/rinstall) and [cargo-native-install](https://github.com/chorman0773/cargo-native-install/).

rinstall is my project so I am biased towards it, as it also supports user-wide installation that might be preferred for psst until is packaged by most distro. If you'd like to, I can add rinstall support for psst. But feel free to choose whatever you prefer.

**Comment by jpochyla** [comment]
@DanySpin97 thanks for the suggestion, but isn't the Linux packing mostly a responsibility of the distributions? We build the .deb in the CI, and i'd be glad to include i.e. RPM, but I'm not sure we need something more complicated. Especially now, in the alpha stage. Anyway, we we have #16 open for this.

**Comment by DanySpin97** [comment]
> Linux packing mostly a responsibility of the distributions?

No, installation is the responsibility of the developer.

>  We build the .deb in the CI, and i'd be glad to include i.e. RPM, but I'm not sure we need something more complicated.

There are tons of distributions out there that don't use deb. You can ship a `psst.spec` file for building the RPM but just few distributions that support RPM. In the `psst.spec` you should install psst by running `install` for each file and directory, which is the same thing that usually `make install` does. Cast aside that, both `rinstall` and `cargo-native-install` are really simple to setup.

**Comment by DanySpin97** [comment]
Btw, #16 is for a different thing. Bundle != packaging and installation.

**Comment by pablodz** [comment]
Do you mean this image?

![](https://imgur.com/1KsCmAI.png)

**Comment by flotwig** [comment]
> We have a .desktop included in the .deb, is something wrong with it?

@jpochyla It's not being installed on Ubuntu, the app has no global desktop entry. Hence this issue, which probably doesn't need to be closed yet.

> .deb represents only a small fraction of all the Linux distributions and UNIX systems. On all other systems there should be a build system/installation script.

@DanySpin97 Ubuntu is the most widely used desktop Linux distro and it is Debian-based, so it's probably good for the .deb to work correctly.

**Comment by jpochyla** [comment]
@flotwig Look, I'm developing and using Psst on Mac, and Linux support is strictly community-driven. If there's something wrong with the .deb, or just doesn't suite you, please open a PR.

**Comment by flotwig** [comment]
Until a PR closes this issue, it would be best to keep this issue open to track it so new reporters don't duplicate this issue.
