### ISSUE TITLE
Readme enhancement

### ISSUE THREAD

**Issue by Hammster** [jpochyla/psst#151]
Hi, I've just stumbled upon this project, very cool!

But one thing is a bit misleading, since the official Spotify client uses CEF not electron.

> Fast Spotify client with native GUI, __*without Electron*__, built in ...

Sure, you're not relating to the official client instead just want to distance yourself from electron there, but it would actually be nice to at least list CEF too :)

Cheers

**Comment by jpochyla** [comment]
It's a remark about a majority of recent multi-platform GUI apps being Electron-based, not necessarily about the official app itself. Thanks for the suggestion, I think we can leave it as is for now.
