### ISSUE TITLE
 failed to start device: generic

### ISSUE THREAD

**Issue by pablodz** [jpochyla/psst#152]
Hello there,

I was using psst as usual, but today I'm getting the error when I try to play a song even if I restart the app or not

```log
[2021-08-27T15:05:46Z ERROR psst_core::audio_output] failed to start device: generic
```

**Comment by jpochyla** [comment]
Seems like an error in your audio setup?

**Comment by pablodz** [comment]
Yeah, I'll check the audio library used in this project, depends on how is integrated into Linux

**Comment by jpochyla** [comment]
Closing because of the migration to `cpal`. Please open other issue in case of audio problems. Thanks!
