### ISSUE TITLE
Title bar remains white in dark theme

### ISSUE THREAD

**Issue by rashil2000** [jpochyla/psst#153]
![image](https://user-images.githubusercontent.com/46838874/131211660-f3709a6a-994d-4458-93d0-e077b6955af9.png)

This does not look very nice. It should ideally be dark in dark theme (or follow whatever theme OS is in). See the explorer at the right for example.

**Comment by amonforstmann** [comment]
You have to fix that one in the Windows registry yourself.

Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM
Add a 32-bit DWORD with the following name: **AccentColorInactive**
You can then copy over your current **AccentColor** value

**Comment by rashil2000** [comment]
That's not the same thing. I'm not asking for Psst to follow the accent color - it already follows that if you enable this Windows setting:

![image](https://user-images.githubusercontent.com/46838874/132623461-e5798dd9-3c59-4dc2-a52b-da5ce90f84a3.png)

I'm saying that it should have a darker titlebar in dark theme, regardless of this setting. This is purely something that the apps control, Windows does not interfere in this. 

But yes, after opening the issue I realized this is something that should be fixed in Druid upstream.
