### ISSUE TITLE
Crashing when not started as sudo

### ISSUE THREAD

**Issue by felixkiessling** [jpochyla/psst#157]
With the new nightly release, app crashes when I select a category from the sidebar. Opening preferences and entering data works.

Error message: "permission denied"

Doesn't happen when starting in terminal with "sudo".

Platform: Macos Catalina

**Comment by jpochyla** [comment]
Sounds like you don't have the permissions to save the config file?

**Comment by felixkiessling** [comment]
Yes, that seems right. I'm am not sure if I can contribute to solve this.

**Comment by jpochyla** [comment]
Unfortunately I'm not sure why that would be the case, Psst is trying to create the config dir in a directory that should be user-writable.
