### ISSUE TITLE
PSST MENUBAR DUPE

### ISSUE THREAD

**Issue by yavko** [jpochyla/psst#158]
psst menubar icons duplicate???
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/15178513/131441272-8eb08e0c-4a02-417f-9939-b76f15e69deb.png">
idk what it is???

**Comment by jpochyla** [comment]
No idea. System version, does it happen always, etc?

**Comment by yavko** [comment]
I found issue just a compat issue with a macOS mod.
