### ISSUE TITLE
Brew release

### ISSUE THREAD

**Issue by blu3beri** [jpochyla/psst#165]
Hiya!

Great client man, really enjoying it so far. Maybe it is out-of-scope for now, but would you be interested in releasing this package on brew? Helps a lot with updates and easy installation. I have minor experience with releasing on brew so I might be able to take a look if you want me to.

cheers!

**Comment by GiovanniSM20** [comment]
I can help in this process @blu3beri cause I thought the same when testing and came looking for interested people

**Comment by jpochyla** [comment]
Thanks a lot! I'd prefer to wait with a Homebrew release when we have some stable-ish releases ready. Anyway, we already have #53 open for this.
