### ISSUE TITLE
Issue building on Pop-OS

### ISSUE THREAD

**Issue by kd2flz** [jpochyla/psst#17]
Hi, I'm on Pop-OS 20.04, and I get the following error when I try to build the program using ```cargo build --release``` 

```
error[E0658]: `match` is not allowed in a `const fn`
```

Originally I got an open-ssl error, which I got around by installing openssl-dev, but I'm not sure how to get around this one.

While I'm thinking of it, I know this is super early days for this project, but it would be awesome to release the app as a Flatpak. I love the idea, and think it will get heavy use once it is stable.

**Comment by jpochyla** [comment]
Hi! Latest stable version of Rust is needed (`match` is allowed in `const fn` since Rust 1.46). The easiest way to install would be `rustup`. Thanks for being interested :)

**Comment by kd2flz** [comment]
Thanks, I got it to build. It's definitely showing promise! Can't wait until it is feature complete.
