### ISSUE TITLE
Missing "no results" placeholder

### ISSUE THREAD

**Issue by biotechdesigner** [jpochyla/psst#173]
Hi, first of all I love the concept of this app and I will test the app and give feedback to make it better (im a UX/UI designer) 
I noticed that when you search something with no results it will only show you this:
![Captura de Pantalla 2021-09-07 a la(s) 1 11 28 p m](https://user-images.githubusercontent.com/85038276/132391765-3601858a-afa8-49f0-b4a2-ae9b9381af4f.png)

I can make a no results placeholder design and post it here later for someone to introduce it in the app, do you agree?

**Comment by pablodz** [comment]
Maybe you can help with #110

**Comment by jpochyla** [comment]
Yes we can do this, but I don't have any other idea then just "No results" placeholder, maybe bigger and centered. Do you have other ideas?

**Comment by jpochyla** [comment]
Added b9f0073 with a simple "no results" info text. We can improve it in the future!
