### ISSUE TITLE
Global Hotkeys

### ISSUE THREAD

**Issue by EwanGreen4** [jpochyla/psst#175]
Readme says that global hotkeys have been implemented, but mine don't work. There are no settings in the menu for keybind configuration. What are the shortcuts bound to?

**Comment by jpochyla** [comment]
Local hotkeys are currently not configurable, we have #129 open for this. Global hotkeys are a responsibility of the OS, usually the keyboard media keys (such as F7-F9 on Mac) work automatically.

**Comment by EwanGreen4** [comment]
Where can I look into this further?

**Comment by jpochyla** [comment]
Depends on your OS. I'd google something with "media keys" keywords, or MPRIS in case you're on Linux.
