### ISSUE TITLE
"Save Track to Library" doesn't save to user's library

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#181]
The context option for a song doesn't save the song into a user's liked songs. Maybe this is just a filler until liking songs is integrated into the project?

**Comment by jpochyla** [comment]
Nope, not a filler, it should definitely work. Do you see something in the console logs?

**Comment by jacksongoode** [comment]
Ah, yes. I see what you mean. In most cases it does work! But there was some instances last night where it wasn't adding it. I'll check again.
