### ISSUE TITLE
UI Doesn't Refresh When Dragging Between Monitors

### ISSUE THREAD

**Issue by jarretraim** [jpochyla/psst#183]
Macbook Pro running 11.5.2 running newest Psst as of 2021-09-17. I am using my MBP monitor as well as an external monitor connected via USB3 through a docking station. 

The external monitor is my primary so on first opening Psst, the UI looks fine:
https://1drv.ms/u/s!AiwgfBr5Jv2ag_QpJhYO2ySEBhL0Pw?e=XZCh29

When I drag it to my MBP monitor, the UI elements disappear as seen here:
https://1drv.ms/u/s!AiwgfBr5Jv2ag_QqIHSz51THUbIT9w?e=OhUrG4

When I mouse over the screen, the UI elements refresh, but the backgrounds don't render correctly:
https://1drv.ms/u/s!AiwgfBr5Jv2ag_QrcrMXFHP7muLEMA?e=V5hkpe

**Comment by jpochyla** [comment]
Hi @jarretraim! Thanks for the report. This is an unfortunate artefact of the partial paint method we're using on macOS, and needs a bit of investigatoin to solve.

**Comment by jpochyla** [comment]
We should trigger a full repaint on this method: https://developer.apple.com/documentation/appkit/nswindowdelegate/1419267-windowdidchangescreen

Druid macOS rendering code will also probably undergo a full rewrite.

**Comment by Insprill** [comment]
@jarretraim Is this still an issue after 346a729796ecca1e49b7fadfd211b6e330e780cc?

**Comment by literallyjustroy** [comment]
This is no longer happening for me when dragging between a 4k and 1080p monitor though it used to (M1 MacOS 13.2).

**Comment by jacksongoode** [comment]
I really wonder what this artifacting is from...
