### ISSUE TITLE
Add context menu to current song right-click

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#184]
It makes sense to click on the current song (in the playback bar) to jump back to the queue context but I also think that right clicking should provide the same context menu that other songs when right clicked.

**Comment by jpochyla** [comment]
Yup, good idea! This is slightly non-trivial because we currently don't have the the `CommonCtx` in the playback bar.

**Comment by jpochyla** [comment]
Added in a609bc5!

**Comment by jacksongoode** [comment]
Wooo!
