### ISSUE TITLE
Audio playback not detected in KDE media player

### ISSUE THREAD

**Issue by Drarig29** [jpochyla/psst#185]
The Linux desktop environment KDE has a media player in the notification bar. It can show the playing audio and you can control the music with it (play/pause, previous/next tracks).

This is an example with the **regular Spotify app**.

![image](https://user-images.githubusercontent.com/9317502/133933816-1946e530-4af8-44c9-83c0-be8f7b6f8822.png)

But `psst` doesn't show there. And I can't use my KDE global shortcuts to control the audio playback.

**Comment by Drarig29** [comment]
Also, I use `neofetch` in my terminal and the current song wasn't showing.

This is an example with the **regular Spotify app**.

![image](https://user-images.githubusercontent.com/9317502/133934080-b96fc56a-dafc-4339-bde1-0c2d952820e9.png)

So I checked how it works:

https://github.com/dylanaraps/neofetch/blob/429499e9b9b39127a8a781d135cafb6babdea631/neofetch#L2868-L2878

It retrieves the playback with this command:

```bash
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.$(MUSIC_PLAYER) /org/mpris/MediaPlayer2 \
            org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' \
            string:'Metadata'
```

And it works with `psst` as `MUSIC_PLAYER`...

So I don't know what is missing in psst for KDE to be able to detect the audio playback.

**Comment by jpochyla** [comment]
We're using the [souvlaki](https://github.com/Sinono3/souvlaki) crate for this.

**Comment by jpochyla** [comment]
It looks like the souvlaki crate has fixed the issue, but we're intentionally pinned to an older version because `zbus` drags in a ton of cruft. Not sure what to do about this.

**Comment by charliethomson** [comment]
@jpochyla It looks like souvlaki 0.5.0 removes the zbus dep, 0.5.0 also fixes this issue, wanna verify and bump?

**Comment by jpochyla** [comment]
Souvlaki 0.5 is in master already, forgot to close this.
