### ISSUE TITLE
Some songs won't play

### ISSUE THREAD

**Issue by confact** [jpochyla/psst#192]
I got an issue with songs that play in the Spotify app get skipped in Psst. 

Can it be that they use a different encoder?

I would love to play all the songs.

**Comment by confact** [comment]
Tested clearing the cache and that worked. Could it be corrupt files in the cache or something?

I think finding the root cause and also maybe showing some type of info while it failed in the GUI would be good. Might show in the log if run through the terminal but I usually don't run it like that.

**Comment by jpochyla** [comment]
Hi, I'll close this if you don't mind. In case the issue re-appears, we can debug it further.
