### ISSUE TITLE
Library uninitialized unless Saved Tracks or Albums is opened

### ISSUE THREAD

**Issue by martingoe** [jpochyla/psst#196]
I am currently trying to implement parts of the playlist manipulation since I have some spare time and I have come across the following problem:

When manipulating the ui/track.rs menu in track_menu(), the passed library only has `Empty` values. This changes, when the user opens `Saved Tracks` or `Albums`. 

I think this might be similar to #181. 
All in all, this is a great project. Thank you very much!

**Comment by jacksongoode** [comment]
I agree, it might make sense to load the library on init.

**Comment by jpochyla** [comment]
Thanks for the report! I'll fix this as soon as #197 is done.

**Comment by jacksongoode** [comment]
Perhaps the initialization of saved tracks should also include saved albums, and podcasts now?
