### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by SethDusek** [jpochyla/psst#20]
Hello, I have tried using psst but I am unable to connect to Spotify. I believe this is because Spotify now has even stricter region requirements. I tried using proxychains4, but it doesn't seem to work properly with this application. The main Spotify client has an option to select a SOCKS5/SOCKS4/HTTP proxy. Are there any plans to add this to psst as well?

**Comment by jpochyla** [comment]
We could do this, yeah! As we're also using a TCP session to talk to Spotify, SOCKS would be needed, right?

**Comment by SethDusek** [comment]
Yea I think so. I personally use my VPS + ssh SOCKS5 to get around the region restrictions

**Comment by jpochyla** [comment]
I've looked into this a bit and while HTTP proxy would be possible to use as well, SOCKS5 would be easiest to implement. I'll get to it through the next week.

**Comment by jpochyla** [comment]
I have a SOCKS5 support implemented for the TCP session and the CDN connections, but the Spotify WebAPI would need a small PR for `aspotify`, so it will take a couple more days, but it's close.

**Comment by jpochyla** [comment]
Hah, sorry, that took longer then expected :) I've completely removed `aspotify` and we do our own thing now. If you're still interested and feel adventurous, try latest master. I haven't tested it yet, but setting `SOCKS_PROXY` and var to smth. like `socks5://john:smith@socks.google.com` should work.

**Comment by jpochyla** [comment]
Closing, feel free to open in case of any issues!

**Comment by aslafy-z** [comment]
This issue should be reopened since support for HTTP proxy is not present. I had a look to ureq, it seems that it won't be implemented from now on, see https://github.com/algesten/ureq/issues/62. What were the reasons behind the choice of ureq? It looks like https://github.com/seanmonstar/reqwest for example has many more features (including http_proxy support) and is better supported.

**Comment by jpochyla** [comment]
`reqwest` is an async client, we need only sync interface.

**Comment by Metacinnabar** [comment]
HTTP proxy support would be great!
