### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by johndoe432** [jpochyla/psst#205]
As I know this app is a privacy-respecting Spotify client, but I think it would be great to have some sort of privacy policy for a user. 

Does Psst have a privacy policy? If it does not, could it be created?

Thanks in advance for your response!

**Comment by jpochyla** [comment]
Hi @johndoe432, thanks for the suggestion, I've mentioned the privacy policy in the README: 

> Psst connects only to the official Spotify servers, and does not call home. Cache of various things is stored locally, and can be deleted at any time. User credentials are not stored at all (re-usable authentication token from Spotify is used instead).
