### ISSUE TITLE
Playback shuffle and looping controls

### ISSUE THREAD

**Issue by reynn** [jpochyla/psst#21]
So far this has been great for me, minimal issues. One thing that is keeping this from being the only thing I use is a shuffle/random option. I was looking through the code and would like to contribute code for this purpose. If this is good with you I'll spend some time looking through code to find places to update but any info would be great!

I do see there are SVG icons for the control buttons, how were these generated in case we will  need more?

**Comment by jpochyla** [comment]
Hi, happy that you like it! Although I don't use them myself, both looping and shuffling would be good to have, I agree. I think I'll eventually get to it, but if you'd like to try yourself, probably the `Queue` struct in `audio_player.rs` would be the place for this. Is looping and shuffling mutually exclusive? First idea is to add a `QueueBehaviour` enum to the queue with variants in like of `Sequential, Random, LoopTrack, LoopQueue` and control it with `AudioPlayer` commands.

All the icons are either from https://ionicons.com Figma plugin, or custom-drawn.

**Comment by reynn** [comment]
Thanks! I'll try to tackle this over the weekend and hopefully get a PR up for you

**Comment by jpochyla** [comment]
Initial playback looping/shuffle has been merged in. @reynn please test, so we can either close this or improve it, thanks!

**Comment by reynn** [comment]
Thanks I'll take a look, sorry this was so delayed I was working on another project briefly

**Comment by reynn** [comment]
For the most part this works, there is just a small bug with looping in that it never seems to play the last track. I put up PR #31  to attempt a resolution.

**Comment by jpochyla** [comment]
Hi @reynn, I've tried to improve the queue behaviour a little in 9c5767ab7, `Random` now plays a shuffled queue instead of random tracks (and finishes after playing the last one), `LoopTrack` now supports Previous/Next buttons.
