### ISSUE TITLE
App does not open

### ISSUE THREAD

**Issue by johndoe432** [jpochyla/psst#210]
Downloaded the latest pre-built binary of Psst. When double-clicking on the icon app just doesn't open

**Comment by jpochyla** [comment]
What OS are you on?

**Comment by johndoe432** [comment]
Windows 10 21H1

**Comment by johndoe432** [comment]
The crash began to happen after I "updated" the Psst to the version that. as far as I know, have today's commits in it

**Comment by vuon9** [comment]
I got the same issue. Both try from the built locally and also on the latest built download via Github. It just can't work!

**Comment by paolobarbolini** [comment]
It'd be helpful to launch it from the terminal and see if it logs anything useful

**Comment by vuon9** [comment]
Last master built has been failed, can't open
```
warning: `psst-gui` (bin "psst-gui") generated 5 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 4m 05s
➜  psst git:(master) psst-gui.exe
```

Here is when running in dev
```
➜  psst git:(master) cd .\psst-gui\
➜  psst-gui git:(master) cargo run
warning: associated function is never used: `channels`
  --> psst-core\src\audio_decode.rs:59:8
   |
59 |     fn channels(&self) -> u8 {
   |        ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `sample_rate`
  --> psst-core\src\audio_decode.rs:63:8
   |
63 |     fn sample_rate(&self) -> u32 {
   |        ^^^^^^^^^^^

warning: `psst-core` (lib) generated 2 warnings
warning: unused import: `OffsetDateTime`
  --> psst-gui\src\data\utils.rs:10:25
   |
10 | use time::{Date, Month, OffsetDateTime};
   |                         ^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: use of deprecated constant `druid::commands::HIDE_APPLICATION`: HIDE_APPLICATION is only supported on macOS
  --> psst-gui\src\ui\menu.rs:32:36
   |
32 |                 .command(commands::HIDE_APPLICATION)
   |                                    ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: associated function is never used: `ctx`
  --> psst-gui\src\data\ctx.rs:30:12
   |
30 |     pub fn ctx() -> impl Lens<Self, C> {
   |            ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `is_cached`
  --> psst-gui\src\data\utils.rs:34:12
   |
34 |     pub fn is_cached(&self) -> bool {
   |            ^^^^^^^^^

warning: variant is never constructed: `Stroke`
   --> psst-gui\src\widget\icons.rs:124:5
    |
124 |     Stroke { width: f64 },
    |     ^^^^^^^^^^^^^^^^^^^^^

warning: `psst-gui` (bin "psst-gui") generated 5 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
     Running `D:\workspace\github.com\jpochyla\psst\target\debug\psst-gui.exe`
[2021-11-12T19:42:58Z INFO  psst_gui::data::config] loading config: "C:\\Users\\quocv\\AppData\\Roaming\\Psst\\config.json"
[2021-11-12T19:42:58Z INFO  psst_core::cache] using cache: "C:\\Users\\quocv\\AppData\\Local\\Psst"
[2021-11-12T19:42:58Z INFO  psst_gui::data::config] saved config: "C:\\Users\\quocv\\AppData\\Roaming\\Psst\\config.json"
[2021-11-12T19:42:58Z INFO  psst_core::access_token] access token expired, requesting
[2021-11-12T19:42:58Z INFO  psst_core::access_token] access token expired, requesting
[2021-11-12T19:42:58Z ERROR psst_gui::widget::promise] async: WebApiError("failed to fill whole buffer")
[2021-11-12T19:43:17Z INFO  psst_core::access_token] access token expired, requesting
[2021-11-12T19:43:19Z INFO  psst_core::audio_file] blocked at 5570528
[2021-11-12T19:43:19Z INFO  psst_core::audio_player] starting playback
[2021-11-12T19:43:19Z INFO  psst_gui::controller::playback] playing
[2021-11-12T19:43:21Z INFO  psst_core::audio_player] pausing playback```

Its UI
![image](https://user-images.githubusercontent.com/3168632/141525871-23757a24-e438-4247-8bb8-ee8644669549.png)

I don't know Rust, so if any way to let it give more log details, then pls let me know.

**Comment by paolobarbolini** [comment]
> async: WebApiError("failed to fill whole buffer")

In my limited experience with psst this line seems to be the most likely cause of the issue. @guerinoni might be interesting to look into next time, unless somebody else gets to this earlier than us.

**Comment by Heychsea** [comment]
Does not launch at all on Win 10 (21H2). Building myself produces the same result (Instantly returns 101). Interestingly, it starts in debug mode...

**Comment by CptPotato** [comment]
This appears to be a problem related to `env_logger` on windows: [rust-lang/rust#88576](https://github.com/rust-lang/rust/issues/88576).

It's fixed in the current `1.58.0-nightly` (tested with `dd549dcab 2021-11-25`) and should also be resolved in `1.57.0` if I understand correctly.

**Comment by xconverge** [comment]
CI seems to use the latest stable, and 1.57.0 looks to be released in the next few days, so we can just hope that the windows binary fixes itself once that happens...maybe?

**Comment by MoriTanosuke** [comment]
1.57.0 is released https://github.com/rust-lang/rust/releases/tag/1.57.0

**Comment by xconverge** [comment]
CI is failing for windows so I don't think that EXE is using 1.57.0 yet? I think the nightly is not actually nightly, it is triggered by an action on commits and is more of a "development" build than a literal "nightly" build, if anyone knows that this is wrong thumbs down and I will delete it but It is what I saw/assume.

**Comment by MoriTanosuke** [comment]
Looks like a file is missing from the current `master` branch:

> error RC2135 : file not found: assets/logo.ico

There are a bunch of PNG files, but no ICO: https://github.com/jpochyla/psst/tree/master/psst-gui/assets

**Comment by CptPotato** [comment]
CI is passing and the windows build works again for me. I think this can be closed now.

**Comment by jpochyla** [comment]
Thanks for the report, closing! <3
