### ISSUE TITLE
Stream is at a 44.1 with parent running at 48, high pitched playback

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#212]
I guess with the new backend the default playback rate is 44.1 and maybe resampling hasn been fully tested? I am on F35 with Pipewire 0.3.40.

**Comment by jpochyla** [comment]
I've tested with outputs at 44.1 and 48 kHz and resampling did kick in, strange :/ Same bug as #214 I guess.

**Comment by jpochyla** [comment]
Let's continue in #214.
