### ISSUE TITLE
Albums longer than 50 tracks won't display the songs remaining

### ISSUE THREAD

**Issue by deekCE** [jpochyla/psst#213]
### Description:
Any album that has more than 50 tracks won't display the rest of songs, thus these songs cannot be played.

### To reproduce:
Going to any album of a length of 50+ tracks (i.e. Undertale's Soundtrack).

### Expected behaviour:
For psst to display more than 50 songs per album.

### Screenshot:
![psst](https://user-images.githubusercontent.com/49599456/142026457-71609fbd-b14b-4406-8f54-ba83e6f1808b.png)

### Environment:
 - OS: Artix Linux x86_64
 - Kernel version: 5.14.16-artix1-1

**Comment by jpochyla** [comment]
Hi, thanks for the report, there is already #18 open for this.
