### ISSUE TITLE
Non-stereo audio outputs don't work

### ISSUE THREAD

**Issue by dmilith** [jpochyla/psst#214]
**Describe the bug**
Every song is resampled to a much higher pitch (big playback speedup)

**To Reproduce**
Just compile master (96059d95d6a69294c0847bfd0f67d0f6dda11e47) and play anything on Mac.

**Expected behavior**
Regular play like after reset to 697c61aa052cf9b6a63c8d6090dc8b5bcb01cd75

**Environment**
 - OS:  macOS on M1
 - Version: 12.0.1 Monterey

**Additional context**
Unsure it's relevant, but all my devices work in 44.1kHz mode (set via Audio Midi Setup app)

**Comment by jpochyla** [comment]
Strange, I have the exact same setup, and it ofc works correctly. With 44.1kHz output it shouldn't even resample.

**Comment by jpochyla** [comment]
@dmilith What number of channels do you get at line `opening output stream: StreamConfig { ...` from the log, please?

**Comment by dmilith** [comment]
@jpochyla Looks good… but doesn't play right:

```[2021-11-17T08:44:00Z INFO  psst_gui::data::config] loading config: "/Users/dmilith/Library/Application Support/Psst/config.json"
[2021-11-17T08:44:00Z INFO  psst_core::audio::output] using audio device: "Komplete Audio 6"
[2021-11-17T08:44:00Z INFO  psst_core::cache] using cache: "/Users/dmilith/Library/Caches/Psst"
[2021-11-17T08:44:00Z INFO  psst_core::audio::output] opening output stream: StreamConfig { channels: 6, sample_rate: SampleRate(44100), buffer_size: Default }
[2021-11-17T08:44:00Z INFO  psst_gui::data::config] saved config: "/Users/dmilith/Library/Application Support/Psst/config.json"
[2021-11-17T08:44:00Z INFO  psst_core::session::access_token] access token expired, requesting```

**Comment by dmilith** [comment]
My config part (excluding credentials):
```json
"audio_quality": "High",
"theme": "Dark",
"volume": 1.0,
"last_route": "SavedTracks",
"queue_behavior": "Sequential"
```

**Comment by dmilith** [comment]
Unsure why it sees 6 channels, where I have only 2 (stereo)

**Comment by jpochyla** [comment]
Oooooh, that's it :)

**Comment by jpochyla** [comment]
Can you please try with 6e65010 (master)?

**Comment by dmilith** [comment]
Still detects 6 channels, still the same output.

**Comment by paolobarbolini** [comment]
> Can you please try with [6e65010](https://github.com/jpochyla/psst/commit/6e650108c5cdec84cdc4b1a0d112a4635e9a1c0c) (master)?

I was about to report the same issue with your last commit fixed it. I'm on Ubuntu 21.10 BTW

**Comment by dmilith** [comment]
I think it may be specific to my sound card… which indeed is 6 channels, but only first two are used for my stereo setup.

**Comment by thebiblelover7** [comment]
Can reproduce on linux. At least I can hear the audio at a much higher pitch than the original.

**Comment by thebiblelover7** [comment]
Oops, spoke too soon, it works on the latest branch (master).

**Comment by jpochyla** [comment]
@dmilith can you please try branch `stereo_map`? I've added some simple channel mapping that just copies left/right and mutes the remaining channels.

**Comment by dmilith** [comment]
@jpochyla Works like a charm on the stereo_map branch!

**Comment by jpochyla** [comment]
@dmilith Merged to master :) The mapping is really rudimentary and the whole audio filter pipeline a bit messy, but at least it works.
