### ISSUE TITLE
How to build an .exe yourself?

### ISSUE THREAD

**Issue by johndoe432** [jpochyla/psst#217]
How can I biuld an executable for windows? Do I need any external libraries or utilities or it can be done without downloading a thing?

**Comment by jpochyla** [comment]
Hi, it's mentioned in the readme:

```
git submodule update --recursive --init
cargo build --release
```

**Comment by johndoe432** [comment]
> 
> 
> Hi, it's mentioned in the readme:
> 
> ```
> git submodule update --recursive --init
> cargo build --release
> ```

Oh, my bad. Thought it was just the other version. Thanks for your help!
