### ISSUE TITLE
psst only shows first 200 items of a playlist

### ISSUE THREAD

**Issue by AdrianHTML** [jpochyla/psst#223]
I have a playlist with 300 items but psst only displays the first 200. 
I worked with the Spotify api as well but with python. It might be because of the request limit. 

ps.: I really like this app. It is very clean and absolutely does what it should

**Comment by jacksongoode** [comment]
I'm sure there is a limit to the number of songs returned from the API call - but I'm not sure if @jpochyla has implemented a way of loading more songs either through pagination or loading once reaching the bottom of the playlist.

**Comment by jpochyla** [comment]
Hi, yes there's a hard limit for now, unfortunately. With the latests patches to Piet, creating text layouts on macOS is fast again, so unless similar problems are present on Win/Linux, we can increase the limit to i.e. 500, for Liked Songs and playlists. Better solution would be indeed either paging or virtual scrolling container (hard to do but possible) + automatic playback when the end of the playlist is reached.

**Comment by jpochyla** [comment]
I've increased the limit in 74c30b09f53f9a701a2f214d79fdd9b102f9c018.

**Comment by jpochyla** [comment]
I'll close this, as we have #18 open for this anyway.
