### ISSUE TITLE
Search doesn't unfocus

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#224]
**Describe the bug**
Once the search bar has been focused, no other interaction will cause the search to unfocus.

**To Reproduce**
1. Focus on search bar
2. ...

**Expected behavior**
When a user selects other elements away from the search bar, the focus should be lost.

**Environment**
 - OS: Fedora 35
 - Version: Latest

**Comment by jpochyla** [comment]
You can resign the focus by pressing Escape. I know it's a bit unfortunate but thats the way it is for now, Druid does not have any concept of ambient focus.

**Comment by jacksongoode** [comment]
Maybe [this PR](https://github.com/linebender/druid/pull/1089) would be one solution?
