### ISSUE TITLE
Build failing on Debian

### ISSUE THREAD

**Issue by lamg** [jpochyla/psst#23]
## Problem
On LMDE 4, building in release mode fails with 
```
 run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"
```

## Solution
Installing `libssl-dev` package fixes the error. Probably adding some documentation about it would be enough.

## Notes
After continuing with the build also needed to install `libgtk-3-dev`, `libcairo2-dev`

**Comment by jpochyla** [comment]
Thank you! <3 I've mentioned the packages in the README: f385390.
