### ISSUE TITLE
App window does not reappear on Mac if closed via top-left "red cross" button

### ISSUE THREAD

**Issue by Rulikkk** [jpochyla/psst#231]
Great app! Finally, something that can play Spotify on a Mac without eating up CPU.

**Describe the bug**
App window does not reappear on Mac if closed via top-left "red cross" button.

**To Reproduce**
1. Run on Mac
2. Start playback (I assume this is optional step)
3. Click the close button (red cross) in the top-left corner of the window
4. Click app icon in the dock

**Expected behavior**
Expected: App window to be shown again on screen. 
Actual: Nothing happens.

**Environment**
 - OS: MacOS Monterrey 
 - Version: 12.01

**Comment by jpochyla** [comment]
Hi, thanks for the report! We already have #139 open for this.
