### ISSUE TITLE
Shuffle does not persist correctly through application restarts

### ISSUE THREAD

**Issue by xconverge** [jpochyla/psst#234]
**Describe the bug**
Shuffle state does not match the UI after an application restart

**To Reproduce**
Open psst, change mode to shuffle, open a playlist, play song 1, press next song, it does not play song 2 (because it shuffled)
Close psst, shuffle is shown as active, open a playlist, play song 1, press next song, it plays song 2 (and shuffle is not actually enabled)
Cycle through the shuffle icon again to get it back to shuffle and it is good again

**Expected behavior**
Playback mode matches the icon

**Environment**
 - OS: Windows 11
 - Version: nightly psst

**Comment by xconverge** [comment]
I looked at QueueBehavior a bit, I also am not sure repeat single track is working

**Comment by jpochyla** [comment]
Hi, thanks for the report, queue mode is not persisted now, yes. I'm currently busy with other things, but expect to include in the persisted state later.

> I also am not sure repeat single track is working correctly

In what way?

**Comment by xconverge** [comment]
> Hi, thanks for the report, queue mode is not persisted now, yes. I'm currently busy with other things, but expect to include in the persisted state later.
> 
> > I also am not sure repeat single track is working correctly
> 
> In what way?

I enabled it and dragged the slider to the end of the song and when it played the next song it was a different song, not sure

Regarding shuffle, currently the icon state IS restored though, so should that be commented out maybe and the icon defaults to regular playback queue mode

**Comment by kingosticks** [comment]
> I enabled it and dragged the slider to the end of the song and when it played the next song it was a different song, not sure

Works perfectly for me.
