### ISSUE TITLE
Preferences Window too small

### ISSUE THREAD

**Issue by myphs** [jpochyla/psst#240]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/12158101/147235516-7bc8b0fa-9b4e-461d-ad67-7949369b6d1f.png)
Notice how high audio quality cannot be selected.

**Expected behavior**
![grafik](https://user-images.githubusercontent.com/12158101/147235706-6faa8704-6dc1-4a35-b134-7e6357377b9b.png)
(Force resized windows with AltDrag)

**Comment by jpochyla** [comment]
Hi @myphs, does the latest master fix this for you? Thanks!

**Comment by myphs** [comment]
Good enough!
Thanks!
![grafik](https://user-images.githubusercontent.com/12158101/147355451-44005a1a-3f0b-441a-a766-a6e0737b2129.png)
