### ISSUE TITLE
Nested playlist support

### ISSUE THREAD

**Issue by glennlunder** [jpochyla/psst#243]
**Is your feature request related to a problem? Please describe.**
On the "normal" Spotify app, there is nested, hierarchical playlists, which I find crucial to organizing my lists. In Psst currently, there is just a long list of them with no subfolders, making navigating more of a chore.

**Describe the solution you'd like**
If Psst could pull those from Spotify, an additionally allow the creation of them, that'd be a crucial feature for me to adopting full-time.

**Additional context**
This is what it looks like on the Spotify desktop app here:

![image](https://user-images.githubusercontent.com/2839057/147826420-aa6a1611-0b0e-43f9-a9d3-ca4281db4140.png)

**Comment by jpochyla** [comment]
Hi, we already have #85 open for this. Thanks for the detailed report!
