### ISSUE TITLE
Playlist order songs by "date added"

### ISSUE THREAD

**Issue by maffelbaffel** [jpochyla/psst#254]
**Is your feature request related to a problem? Please describe.**
My spotify playlists used to be ordered by "date added" descending (latest at the top of the playlist). This allowed me to play the latest added songs of a playlist first, the queue was also filled with latest first and oldest last. This is really convenient if you have a really large playlist and want to play the latest added songs.

**Describe the solution you'd like**
* I would be nice to have an **order option per playlist** which allows to order the playlist. Ordering by **date added ascending/descending** would be sufficient for me.
* Clicking a song and adding it to the queue should the respect the ordering. E.g. if ordered by latest songs first, play latest songs first then older songs.

**Describe alternatives you've considered**
Psst currently does not have a alternative.

**Additional context**
See the official spotify client for that feature.

**Comment by Insprill** [comment]
Closed by #392
