### ISSUE TITLE
MacOS: Audio switch

### ISSUE THREAD

**Issue by Tazi0** [jpochyla/psst#263]
**Describe the bug**
While connecting to a Bluetooth device with Psst open, it doesn't change device. The OS says that audio goes through the new Bluetooth device

**To Reproduce**
1. Open Psst
2. Play a song
3. Pause the song
2. Connect audio device
3. Play the song

**Expected behavior**
It's expected to switch the audio without issue

**Environment**
 - OS: MacOS
 - Version: Monterey v12.1

**Comment by jpochyla** [comment]
Hi, thanks for the report, we already have #215 for this.
