### ISSUE TITLE
Artist Page: Move list of singles to immediately after list of albums

### ISSUE THREAD

**Issue by dmoa** [jpochyla/psst#265]
![example_spotify](https://user-images.githubusercontent.com/44374106/150220104-86b5f783-cb34-4790-836b-ef10231ffd69.png)

I'm aware singles are below the "appears on" list, but it may be more convenient to place singles above a less commonly used list.

**Comment by charliethomson** [comment]
Looks like it's a Spotify thing. 
![image](https://user-images.githubusercontent.com/38197300/150235549-b4d6a925-954d-46a9-af74-5734fc333893.png)
They seem to be marking 'appears on' albums as 'albums' 

by no means is this a good way to solve this issue, but it works for coldplay as far as I can tell
![image](https://user-images.githubusercontent.com/38197300/150236061-44d6ba40-5138-415b-bc12-0e0c62f75d0f.png)
![image](https://user-images.githubusercontent.com/38197300/150235990-ec11c352-f551-4b32-9836-70debf1799a8.png)

I also added a section at the bottom for 'appears on' albums 
![image](https://user-images.githubusercontent.com/38197300/150236174-5f86e181-0c66-4405-8b4e-b25b62eda558.png)
![image](https://user-images.githubusercontent.com/38197300/150236141-3f609ac8-570f-4813-8fb3-2ddf1a8bc08d.png)

@jpochyla:
this is a bit of a hacky way to do this, any ideas?

**Comment by jacksongoode** [comment]
Nice - I was just about to open an issue on this!

**Comment by Insprill** [comment]
Closed with #271
