### ISSUE TITLE
Bug report: Podcasts have no description limit

### ISSUE THREAD

**Issue by onkoe** [jpochyla/psst#269]
**Describe the bug**
When selecting a podcast, the full description of the podcast is shown. For some shows, this is a non-issue, but others make use of SEO or even give a summary of all discussed events with their descriptions. As such, it is much too long in some cases. Shorten

**To Reproduce**
Find a podcast (in this case, The Majority Report) with a long description. It will fill a significant portion of your screen. This happens on both Fedora (Linux) and Windows clients. 
**Expected behavior**
Cut off or truncate the description into a "Read more..." button so that shows may be browsed with leisure. 

**Screenshots**
![image](https://user-images.githubusercontent.com/66580279/150455165-cb11d721-167a-4956-beb7-e3a4d669cb0f.png)

**Environment**
 - OS: Fedora Linux 35, Windows 10 LTSC IoT 21H2
 - Version: [CI 260](https://github.com/jpochyla/psst/actions/runs/1722047756), "Podcast/Show support" build

**Additional context**
N/A

**Comment by jpochyla** [comment]
I've limited the podcast description to 2 lines in master. In the future, proper episode detail will get implemented.
