### ISSUE TITLE
Is the windows version working on windows 11?

### ISSUE THREAD

**Issue by aaryanporwal** [jpochyla/psst#270]
I tried to use the Psst.exe.zip release from https://nightly.link/jpochyla/psst/workflows/build/master. But I couldn't make it work.
I unzipped and tried to run and I even renamed Psst.exe.zip to Psst.exe and it still wouldn't run.
Any help would be appreciated.
Thanks!

**Comment by jpochyla** [comment]
Hi @aaryanporwal, unfortunately I have no way to test. Anybody else?

**Comment by creinholdsson** [comment]
I tried it today on Windows 11 build 22000.376 and it works.
Not sure what you mean with "I even renamed Psst.exe.zip to Psst.exe and it still wouldn't run".

If you unzip Psst.exe.zip there is a file inside called `psst-gui.exe` .
If `psst-gui.exe` still won't run, can you try run it from Powershell or similar and see if you get some error output?

**Comment by aaryanporwal** [comment]
> I tried it today on Windows 11 build 22000.376 and it works. Not sure what you mean with "I even renamed Psst.exe.zip to Psst.exe and it still wouldn't run".
> 
> If you unzip Psst.exe.zip there is a file inside called `psst-gui.exe` . If `psst-gui.exe` still won't run, can you try run it from Powershell or similar and see if you get some error output?

The thing is, I'm not even able to unzip the zip file:
![image](https://user-images.githubusercontent.com/54525904/150831179-056abd06-49d8-4178-b9bc-bb9156d354ca.png)
![image](https://user-images.githubusercontent.com/54525904/150831262-c90faaec-4529-402b-8b9e-4fba5033b262.png)

**Comment by aaryanporwal** [comment]
7 zip was able to (I think partially) unzip the file, but even then when I try to run the psst-gui.exe file, I get the following error:
```
ResourceUnavailable: Program 'psst-gui.exe' failed to run: An error occurred trying to start process 'C:\Users\abc\Downloads\Psst.exe\psst-gui.exe' with working directory 'C:\Users\abc\Downloads\Psst.exe'. The specified executable is not a valid application for this OS platform.At line:1 char:1
+ .\psst-gui.exe
+ ~~~~~~~~~~~~~~.```
![image](https://user-images.githubusercontent.com/54525904/150831680-eda6271f-ecf3-43eb-bf3a-9b77dcdd6f7b.png)

**Comment by jpochyla** [comment]
Seems like you downloaded a corrupted archive, please try again.

**Comment by aaryanporwal** [comment]
> Seems like you downloaded a corrupted archive, please try again.

Is there any other archive present other than the one on https://nightly.link/jpochyla/psst/workflows/build/master

**Comment by aaryanporwal** [comment]
Okay I figured it out! The problem was chrome didn't like the file and was intentionally corrupting it because of the suffix `.exe`.

**Comment by NineXYZ** [comment]
Simple advice… Stop using Chrome and the unwanted download blocker (something like that is the name), if you don't trust a file just don't download it or use virus total.

**Comment by aaryanporwal** [comment]
It wasn't a download blocker or any other third party software, apparently it's an inbuilt feature in chrome.
And as far as I know, Google hasn't publicly shared how that detection works or what specifically determines when the warning is triggered.
