### ISSUE TITLE
Search Saved Tracks

### ISSUE THREAD

**Issue by confact** [jpochyla/psst#273]
**Is your feature request related to a problem? Please describe.**
I try to find a track in my huge saved track list, I would like the Search like you can do on Spotify.

**Describe the solution you'd like**
Have a way to search or filter the saved Track list or other lists if it makes sense. 

**Describe alternatives you've considered**
Scrolling looking for the track in the list is hard.

**Comment by jpochyla** [comment]
Hi, I've just added the find dialog into Saved Tracks in 1627cd4. It's the same code as for playlists, and is quite rudimentary for now. I'll polish it a bit before the beta release.

**Comment by confact** [comment]
@jpochyla I downloaded the latest binary build but can't see a search, and when clicking on a Saved Track to play, it crashes.

Not sure if it is connected to this issue.

**Comment by confact** [comment]
Never mind, I think it was another bug I found; I went away and came back, and it is working again. If I can reproduce it, I will create an issue for it.

**Comment by jacksongoode** [comment]
How does this search work? Is it a menu command?

**Comment by confact** [comment]
@jacksongoode It is added as a section in the normal search. It has to get better; it would be friendly with just a filter in the liked songs. Search is hard to navigate now.

**Comment by RichardFevrier** [comment]
Don't see it in the latest release, has it been removed @confact ? =)
