### ISSUE TITLE
Incorrect repainting while scrolling playlists

### ISSUE THREAD

**Issue by adamsoutar** [jpochyla/psst#281]
**Describe the bug**
If you leave your cursor hovered over a track and scroll using the scroll-wheel (or a trackpad gesture in my case), it paints the hover state over multiple songs. I would expect it to only be one track at a time, like it does when you move the mouse without scrolling.

I wondered if this was a bug in druid, but it does not happen on the playlist sidebar, only the tracks.

**Screenshots**

![psst-bug-2](https://user-images.githubusercontent.com/26578100/154840392-7a127fc8-e9f7-41f6-895e-e5c0aed1a7f1.gif)

**Environment**
 - OS: macOS Monterey
 - Version: 12.2.1

**Comment by fabian-st** [comment]
Can confirm this issue on Ubuntu 20.04

**Comment by clin045** [comment]
Looks to be related to https://github.com/linebender/druid/issues/2181 in Druid

**Comment by jpochyla** [comment]
Hi, sorry for the wait :( Fixed in master!
