### ISSUE TITLE
Left navbar error: Failed to read JSON

### ISSUE THREAD

**Issue by soyacz** [jpochyla/psst#284]
**Describe the bug**
No info/playlists on left navbar. See screenshot.
`Failed to read JSON: invalid type: null, expected a string at line 18 column 27`

**To Reproduce**
Open `psst`

**Expected behavior**
No error shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/18242288/159218460-7f6dd891-27b4-4228-9204-c9eeb1eab562.png)

**Environment**
 - OS: Linux Mint 
 - Version: 20.3 Cinnamon (5.2.7)
kernel 5.13.0-35

**Additional context**
Thanks for the great work with Psst!!

**Comment by jpochyla** [comment]
Hi @soyacz, sorry about the late reply. Does the problem still persist? Do you get any interesting log output in the console?

**Comment by soyacz** [comment]
Not persisting anymore. Closing.
