### ISSUE TITLE
Double albums

### ISSUE THREAD

**Issue by Tazi0** [jpochyla/psst#287]
**Describe the bug**
For each album there are 2 entries

**To Reproduce**
1. Go to an artist (Gunna for my example)

**Expected behavior**
It should've shown the album just 1 time

**Screenshots**
<img width="486" alt="Screen Shot 2022-03-25 at 10 23 02" src="https://user-images.githubusercontent.com/45716542/160092834-b0987edd-f5ea-45f7-991d-44350df9a782.png">

**Environment**
 - OS: MacOS Monterey
 - Version: v12.2.1

**Comment by clin045** [comment]
This is not a bug in psst. What you're seeing are the explicit and clean versions of the album, which do show up in the official Spotify client as well. 

<img width="895" alt="image" src="https://user-images.githubusercontent.com/7468898/175842351-86d45227-ae5a-4872-9ba9-27fc36ac6cd8.png">

**Comment by Tazi0** [comment]
@clin045 To me, it looks like there aren't "2" albums like you mentioned/see. Maybe it's just hidden for me, but adding a label to the right would clear the double albums up for me.

<img width="1128" alt="Screen Shot 2022-06-30 at 12 49 32" src="https://user-images.githubusercontent.com/45716542/176659447-70eb6487-cc31-47a2-b466-7579e2ae8a14.png">

**Comment by SO9010** [comment]
Can this be closed? @jacksongoode or @Insprill
