### ISSUE TITLE
High CPU usage on Windows (1-3%) 

### ISSUE THREAD

**Issue by snir** [jpochyla/psst#289]
**Describe the bug**
psst-gui.exe is using ~1% CPU when idle, up to ~3% when playing a song.

**To Reproduce**
Run psst.exe on Windows

**Expected behavior**
CPU usage should be much lower (Spotify is using ~0.5% when idle, ~2% when playing a song)

**Screenshots**

**Environment**
 - OS: Windows
 - Version: latest (can't find a version number)

**Additional context**
There seem to be 2 threads using the most CPU - 
1. psst-gui.exe calling `KernelBase.dll!WaitForMultipleObjectsEx`
2. psst-gui.exe calling `user32.dll!GetMessageW`

**Comment by HookedBehemoth** [comment]
I'm running it on Windows and I can't observe this. The official spotify client consistently uses more CPU.
