### ISSUE TITLE
Nightly links not up to date

### ISSUE THREAD

**Issue by xconverge** [jpochyla/psst#295]
https://nightly.link/jpochyla/psst/workflows/build/master does not have the most recent builds/executables as https://github.com/jpochyla/psst/actions/runs/2008968370

The "nightly.link"s are from january and should probably be newer? Not sure how it is plumbed together or supposed to be really but it doesn't seem right currently.

**Comment by alexreyes** [comment]
+1

**Comment by jacksongoode** [comment]
Maybe the build CI is broken?

**Comment by jpochyla** [comment]
Oops, thanks for the heads-up!

**Comment by jpochyla** [comment]
Actually I think it's working correctly now? Maybe a hiccup on nightly.link's side?
