### ISSUE TITLE
Is this project dead or in need of a new maintainer?

### ISSUE THREAD

**Issue by bnwa** [jpochyla/psst#296]

**Comment by jacksongoode** [comment]
It's only been a month since the last commit?

**Comment by jpochyla** [comment]
Hi! I think this is a good question.

The project is definitely **not dead**. I've began to work on Psst during the free time surplus of the first pandemic wave, and recently I haven't had many chances to progress the project -- my daughter was born, I have a new full time job, we were moving a lot, etc. Another big reason Psst haven't seen much development lately is that the shoulders of the giants we're standing on are shaking: Druid is expected to undergo a complete rewrite, cpal lacks the features a serious music player would require (so another library would be needed IMO), etc. So I'm waiting a bit, at least until the timeline of the new Druid architecture is a bit more clear. Psst is still my baby, and I'd love to make it into a perfect music player. Sorry for the hiatus.

**Comment by kingosticks** [comment]
No need to apologise, you don't owe anyone anything. Congrats on your daughter. 

The question might be reasonable but the phrasing comes across as entitled.
