### ISSUE TITLE
Searching for playlists

### ISSUE THREAD

**Issue by shiftgeist** [jpochyla/psst#30]
Is it possible to show user created playlists when searching? Artists, Albums and Tracks already show up when searching.

Thank you for your awesome work so far!

**Comment by jpochyla** [comment]
Thanks for being interested! Yes playlists are missing from the results now, and it's a bit of an oversight.

**Comment by jpochyla** [comment]
Implemented in 562f9df, although the UI is not very pretty yet. The search page needs an overhaul anyway. Ideas welcome!

**Comment by jpochyla** [comment]
@shiftgeist Good idea, done!
