### ISSUE TITLE
Documentation: add a line to install `cargo-bundle`

### ISSUE THREAD

**Issue by rjzak** [jpochyla/psst#300]
**Is your feature request related to a problem? Please describe.**
The documentation says to run `cargo bundle` to create the macOS app bundle, but the `bundle` sub-command is undefined.

**Describe the solution you'd like**
Add a line to the documentation to include the instruction to first run `cargo install cargo-bundle` when compiling on macOS for the first time.

**Describe alternatives you've considered**
Provide Apple Silicon or Universal pre-built binaries via GitHub Actions (if possible).

**Additional context**
N/A

**Comment by jpochyla** [comment]
Good idea, done. Thanks!
