### ISSUE TITLE
Show cover images for saved (favorite) tracks

### ISSUE THREAD

**Issue by fabian-st** [jpochyla/psst#312]
**Is your feature request related to a problem? Please describe.**
It can be hard to spot songs under saved tracks in an instinct because there are no cover images shown unlike in a playlist.

**Describe the solution you'd like**
Display cover images for saved tracks just like it is already the case for playlists.

**Describe alternatives you've considered**
Reading every title (which takes longer) or create a designated favorite playlist in order to see the cover images.

**Additional context**
See screenshots below.

![Screenshot from 2022-06-28 18-57-29](https://user-images.githubusercontent.com/67522364/176240142-f6231b93-ea65-48ab-8107-eee71c753e4c.png)
![Screenshot from 2022-06-28 18-58-19](https://user-images.githubusercontent.com/67522364/176240172-d25a5781-475b-4cfe-983a-9b1b4896ab0a.png)

**Comment by jpochyla** [comment]
Hi @fabian-st, there's an option in the preferences for this already.
