### ISSUE TITLE
Songs not playing on Arch Linux

### ISSUE THREAD

**Issue by mattfj10** [jpochyla/psst#317]
**Describe the bug**
Songs not playing when selecting one in psst

**To Reproduce**
1. Open psst
2. Attempt to play song

**Expected behavior**
1. Open psst
2. Attempt to play song
3. Hear music
**Screenshots**

**Environment**
 - OS: Arch Linux 
 - Version: 5.8.12

**Additional context**
I can't think of much else, playing media seems to work in my web browsers and other players, but for some reason in psst, songs just won't play. I'll select play, but the text indicating the timestamp the music is at will never change from "0:00", and I hear no sound, so from this I deduce music won't play. I tried opening it with a terminal attached to see the output, the closest thing I got to a clue was this error:

```
[ERROR psst_core::audio::output] output stream actor is dead 
```

**Comment by rklasen** [comment]
I've had the same issue, see #230.

In my case it was fixed by installing `pulseaudio-alsa`, see also the [AUR](https://aur.archlinux.org/packages/psst-git).
