### ISSUE TITLE
Why their is a Microphone icon on the top of the left sidebar?

### ISSUE THREAD

**Issue by gagarine** [jpochyla/psst#321]
Not really a bug, but I don't understand why their is a Microphone icon on the top of the left sidebar.

![Screenshot 2022-08-09 at 11 19 20](https://user-images.githubusercontent.com/164074/183613054-5398ff91-0744-487f-9d54-1b0b0ee2a9e6.png)

**Comment by jpochyla** [comment]
It the old placeholder for a logo/icon. I'll replace it some day with a monochrome version of the current icon.

**Comment by gagarine** [comment]
OK! Then I think it would be perfect with nothings ;). Why would a user want an icon at this place?
