### ISSUE TITLE
Ability to enter credentials when "Sign in with Apple" was used for Spotify account

### ISSUE THREAD

**Issue by aashiqsworld** [jpochyla/psst#338]
I'm trying to enter my spotify credentials, but since my spotify account is linked to my Apple ID I'm not sure what to use. I was able to find my private email address that apple uses with spotify, but since they authenticate sign-ins with a token I don't have a password I can provide. 

As far as I can tell no one else has had this issue, so I'm hoping this is a feature you could add. Thanks!!

**Comment by Pogodaanton** [comment]
Hey aashiq,

You can create a password for your Spotify Account by filling out the password reset form with your randomized private apple-generated email address. You will need to have access to the email address you have linked to your Apple account for this. Learn more [https://support.spotify.com/us/article/apple-login-help/](here) under the section "Can’t log in with Apple?"

**Comment by SO9010** [comment]
@jacksongoode isn't this a very similar issue to #462 so maybe we should close this too as there is a solution.

**Comment by jacksongoode** [comment]
Right, I think this is a bit out of scope for now. There might be someway of getting a cookie that we can accept from loading a webpage sign in but that should be much later once things are stable.
