### ISSUE TITLE
psst-gui, Windows: Is this normal? First-launch results in settings

### ISSUE THREAD

**Issue by IngwiePhoenix** [jpochyla/psst#34]
I just `git clone --recursive`'d this repository and ran `cargo build` on it to get myself started. Unfortunately, it feels like something is missing.

Upon launching the app, I only get to see the settings view - and it feels cut off.

![image](https://user-images.githubusercontent.com/2893716/108200626-006cfe80-711f-11eb-8837-2b6131cc1017.png)

Did I skip a step somewhere?

**Comment by Kesefon** [comment]
The Save button seems to be missing on Windows.
![psst3](https://user-images.githubusercontent.com/19211219/105505890-c3515000-5cc9-11eb-949d-2c3d36364355.png)

A workaround is to manually create the config file at
`C:\Users\<username>\AppData\Roaming\Psst\config.json`
with this content:
`{
  "username": "Kesefon",
  "password": "password123"
}`

_Originally posted by @Kesefon in https://github.com/jpochyla/psst/issues/3#issuecomment-765464444_

A proper fix would be to make the window larger.

**Comment by jpochyla** [comment]
Hi, thanks for the report, sorry about the delay. Unfortunately I develop and test the app only on Mac so far, so these issues pop up from time to time. Fix incoming.

**Comment by jpochyla** [comment]
So! Until we can remove the menus (they are needed right now for copy&paste to work), I'll make the Preferences window size itself by the content, so it will fix this. In the future, we can rid of the menus completely, as they're ugly and useless.

**Comment by jpochyla** [comment]
Should be fixed in 0bb5258, I haven't tested on windows, though. Please reopen in case of any similar issues.
