### ISSUE TITLE
Feature request: displaying song lyrics

### ISSUE THREAD

**Issue by gershik** [jpochyla/psst#349]
**Describe the solution you'd like**
Lyrics have been available in all regions for a while. `librespot` seems to support them, so I believe they could be a good addition to the client. If a two-panel layout is implemented, the playback section could display them all the time; otherwise, a button in the playback area could open them full-screen, like in the official Spotify client.

**Comment by cloudybyte** [comment]
There was some discussion regarding merging psst-cores api wrapper/player and librespot in #204, however that was 18 months ago and not much has moved since then.

**Comment by SO9010** [comment]
Spotifys official API is: https://coda.io/@musixmatch/musixmatch-lyrics-api/api-methods-3

**Comment by SO9010** [comment]
I will have a look into this. At the moment I'm thinking we could have another page which is accessed through a toggle then that page could have the lyrics in. 

We can also sync it I'm pretty sure to the timestamp of the song so maybe we can have a condensed view of the lyrics? 

Just brainstorming here. If anyone has any ideas feel free to say them.

**Comment by SO9010** [comment]
This also has links for artists!!!

**Comment by SO9010** [comment]
Wait, this doesn't work I dont think. Im pretty sure we will have to sign up to be a partner. Annoying!

**Comment by SO9010** [comment]
https://github.com/raitonoberu/sptlrx does it!

**Comment by jacksongoode** [comment]
There are some free APIs we can use to fetch the lyrics, we should compile and list and see if we can integrate.

**Comment by kingosticks** [comment]
Am I missing something, why not do the same as librespot?
https://github.com/librespot-org/librespot/blob/118a9e1a516028b75f2dbf7c50ed8a4f28fe20f5/core/src/spclient.rs#L569
and 
https://github.com/librespot-org/librespot/pull/1084/commits/f72048e5e1a6f74c5476eef89a1de37fa7bb118f

**Comment by jacksongoode** [comment]
Oh look at that, yeah you might be right. We should give it a shot!

**Comment by SO9010** [comment]
Yes I just got it to work with a fixed variable for the song and the image, so that's the next things I have to change! It shouldnt take too long.

**Comment by SO9010** [comment]
> Yes I just got it to work with a fixed variable for the song and the image, so that's the next things I have to change! It shouldnt take too long.

As in reverse engeering the Spotify API

**Comment by SO9010** [comment]
This should now be closed. Due to #535
