### ISSUE TITLE
UI glitches while scrolling on MacOS 13 Ventura

### ISSUE THREAD

**Issue by goodness-from-me** [jpochyla/psst#354]
**Describe the bug**
UI is glitchy while scrolling on a new MacOS 13 Ventura.

**To Reproduce**
1. Upgrade your MacOS to 13.0.
2. Launch psst.
3. Use mouse wheel to scroll tracks list or playlist list.

**Expected behavior**
UI should not glitch on scrolling on MacOS 13.0.

**Screenshots**

https://user-images.githubusercontent.com/42966950/197981590-984e10df-1f84-466d-8502-246bbfd45c28.mov

**Environment**
 - OS: MacOS 13.0
 - Version: 20221012.214925

**Additional context**
Running on MacBook Pro 16 (M1 Pro).

**Comment by onpaws** [comment]
+1 

I recently learned became a Psst user and for a little while have been happily using it on macOS 10.12.
Sadly as of 10.13, when I click certain elements there seems to be quite a bit of new flicker and lag in the UI. Almost feels like things are rendering synchronously? (No clue, just guessing.)

When I change tracks it's common for this screen to hang around for "a while", feels like 1s or so, before the usual playback UI "settles"
<img width="640" alt="image" src="https://user-images.githubusercontent.com/182515/198102395-b12a795c-dcac-4685-b0fc-83edca6b5df4.png">

No clue the reason. Happy to provide logs etc if desired. Will still prefer Psst, but will be nice if we can figure it out :)

**Comment by nitantsoni** [comment]
+1 this has started happening for me as well

**Comment by edapm** [comment]
+1 me as well

**Comment by tbeseda** [comment]
I believe this relates to display scaling + high DPI. Since I get glitching and empty UI on high-DPI displays (like the Macbook's screen) but not on displays I use at 1:1 pixel ratio.
(Oct 12 build)

**Comment by jpochyla** [comment]
Hi, @Insprill this is because of my old Druid patch that was improving performance on MacOS by drawing only the damaged regions, but it's clearly OS version-dependent and we should throw it away :/ Psst is using https://github.com/jpochyla/druid/commits/psst, I'll update the branch by removing the commits and grant the same collab rights as here.

**Comment by jpochyla** [comment]
Fixed in 346a729, sorry about the long wait :(

**Comment by gabrielmaldi** [comment]
Just pulled these changes, built, and can confirm it's rendering perfectly now. Thanks!

**Comment by onpaws** [comment]
> Just pulled these changes, built, and can confirm it's rendering perfectly now. Thanks!

+1 thank you for sorting it out 🎉
