### ISSUE TITLE
Authentication failed: premium account required but account is premium

### ISSUE THREAD

**Issue by exur00** [jpochyla/psst#357]
When I try to login with my account it says "error Authentication failed: premium account required"
I don't have a classical premium account but I do have a family premium account.
This used to work, but I haven't used the program in quite a while so I can't pinpoint when it broke.
![image](https://user-images.githubusercontent.com/17301038/199936610-9f38862f-8c0c-41a7-8b93-4ed15be76dba.png)

**Comment by michaelsage** [comment]
Experiencing the same issue, did you manage to resolve the issue?

**Comment by exur00** [comment]
I have not managed to resolve the issue yet.

**Comment by gslin** [comment]
Same issue for psst package in Ubuntu 20.04 (https://packages.ubuntu.com/focal/psst this).  Solved by cloning the repository and compiling by myself.  Also I deleted `~/.config/Psst` and `~/.cache/Psst` to clear login information.

**Comment by exur00** [comment]
>

**Comment by exur00** [comment]
Woops I didn't mean to do that, excuse me.
>Solved by cloning the repository and compiling by myself. Also I deleted ~/.config/Psst and ~/.cache/Psst to clear login information.
This also worked for me (fedora 36), but still I'd rather keep using the snap, if there's any way I can help you find out what's causing this, don't hesitate to tell me what I can do.
