### ISSUE TITLE
saved config on each mouse move while changing geometry

### ISSUE THREAD

**Issue by y0nei** [jpochyla/psst#360]
**Describe the bug**
I have launched the latest appimage today and noticed that on every geometry change, it saves the config

**To Reproduce**
launch appimage from terminal, and play around with the geometry. Now it spams info logs

**Expected behavior**
Brief delay between config writes or some sort of timer to track the end of the window changing its geometry

**Environment**
 - OS: `Linux arch 6.0.11-arch1-1`
 - Version: `Psst-.glibc2.29-x86_64`

**Comment by jacksongoode** [comment]
Likely related to https://github.com/jpochyla/psst/pull/346 @Insprill any thoughts as to why?

**Comment by Insprill** [comment]
Yup that PR would be the cause. I think saving on a graceful close is a fair tradeoff. It's not a huge deal if the app is terminated or crashes and the window size is lost.
