### ISSUE TITLE
Please dont Require Priemium 

### ISSUE THREAD

**Issue by Snowiiii** [jpochyla/psst#376]
Hey i saw in the README stands i need Premium this was a Deal Breaker for Me, But it is Possible to login without Premium like [SpotTube](https://github.com/KRTirtho/spotube) it does

**Comment by shaunsingh** [comment]
You can modify the source code to allow non-premium accounts, but that is breaking spotify TOS

**Comment by Insprill** [comment]
As shaunsingh said, this would violate Spotify's TOS, and we won't be adding it.

**Comment by clippycoder** [comment]
I don't think spotube breaks spotify's TOS. They don't pirate music from spotify, they use spotify's public API to discover tracks, and then stream them from youtube. I'm just pointing that out, not saying that this should be done here.

**Comment by kingosticks** [comment]
> Do not create any product or service which is integrated with streams or content from another service.

https://developer.spotify.com/policy part III.5

To be fair, nearly everything is against their terms. I think you just need to be sensible and avoid attracting attention through obvious violations that take value away from their product/tech.
