### ISSUE TITLE
UI flickering on MacOS

### ISSUE THREAD

**Issue by benmanone** [jpochyla/psst#381]
I don't know if the homebrew cask is official or not, but after installing it on my Macbook the UI elements are turned white and then flicker for a few seconds if I move my mouse quickly over them. Example:

https://user-images.githubusercontent.com/65849005/229578484-64862f86-c3f8-4ade-9145-e3722e271512.mov

**Comment by goodness-from-me** [comment]
Seems like the same as #367

**Comment by benmanone** [comment]
Yeah seems like they're the same.

**Comment by jacksongoode** [comment]
Closing in favor of #367
