### ISSUE TITLE
[Windows] "Failed to fill whole buffer" when trying to sign in

### ISSUE THREAD

**Issue by StoppingBuck** [jpochyla/psst#382]
**Describe the bug**
When trying to log in, the app displays "Failed to fill whole buffer". Nothing else happens

**Screenshots**
![image](https://user-images.githubusercontent.com/8426548/229861066-e371f8fc-d9d4-45ac-a22f-f68216420669.png)

**Environment**
 - OS: Windows 10
 - Version: Latest master build as per 2023-04-04

**Comment by StoppingBuck** [comment]
It is worth mentioning that Windows SmartScreen tried blocking the .exe from being run, and I had to manually select "Run Anyway"

**Comment by cloudybyte** [comment]
Hiding the password/using a protected textbox is not possible as of now, as druid (the GUI framework we use) doesn't support it. There was some discussion around it (and even some first attempts at implementing,  see linebender/druid#1839, linebender/druid#1114 and linebender/druid#2105), but I don't think it's worth it to invest the time as druid is discontinued.

However, I've fixed the broken error message in #386
