### ISSUE TITLE
Saved track icon

### ISSUE THREAD

**Issue by codemonkey91** [jpochyla/psst#388]
**Describe the solution you'd like**
Looking to replicate feature of official Spotify web/client. Spotify uses a little green heart icon beside tracks saved to your collection (ie "liked" tracks). When browsing Psst in any view that displays individual tracks, I would like to see some kind of indicator icon showing whether the track is already saved to my library.

**Describe alternatives you've considered**
Text-based "Saved" indicator beside each track name or beside other track details (Album/Artist/etc).

**Comment by Insprill** [comment]
Duplicate of #248
