### ISSUE TITLE
Impossible to open Preferences on Linux and Windows

### ISSUE THREAD

**Issue by shiftgeist** [jpochyla/psst#39]
rn the window looks like this:

![image](https://user-images.githubusercontent.com/30648730/110635959-fb462100-81ab-11eb-8a95-3f6c57ea10a2.png)

I have not jet found a way to open the settings menu. Light theme hurts :smile: :radioactive: 

I could imagine something like `psst-gui --theme=dark`. 

`psst-gui --help` doesn't seam to be a thing yet since it start the gui normally.

Environment:
Debian 10 (installed via `.deb` package)
Version: `562f9df` (Mar 10, 2021)

**Comment by jpochyla** [comment]
> I have not yet found a way to open the settings menu.

Haha, we should definitely fix this, at the very least the shortcuts should work! Sorry, there isn't any command line handling yet, correct. In the meantime, you can switch the theme in the JSON config file. The path should get printed in the logs.

BTW, most of GTK apps on Linux don't use an application menu anymore, and the global (Mac-like) menu from the old Ubuntu days isn't used either, correct? We could add a hamburger icon to the top-right corner with a context menu for Linux and Windows.

**Comment by shiftgeist** [comment]
Application menu is available in Gnome, but it gets complicated/"i don't know" how when there is a custom desktop environment like dwm envolved.

Hamburger sounds good (food and menu!).

**Comment by jpochyla** [comment]
> Hamburger sounds good (food and menu!).

Oh and while we are at it, the tofu □ characters in place of emojis should get solved soon in Druid (by switching to Pango text rendering.)

**Comment by jpochyla** [comment]
Fixed in 0bb5258, I've added just a "Show Preferences" button instead of a full hamburger, as we don't have anything else to put there now :)

**Comment by shiftgeist** [comment]
![image](https://user-images.githubusercontent.com/30648730/111077592-c3afdf80-84f1-11eb-9a9f-37ccc9686bde.png)

The icon(s?) looks overlayed on windows, not shure if intentional.
