### ISSUE TITLE
Debian/Ubuntu/Mint: conflict with psst package

### ISSUE THREAD

**Issue by tobiasrenkin** [jpochyla/psst#391]
**Describe the bug**
There is an unrelated Debian package called [psst](https://packages.debian.org/sid/devel/psst). If I install the psst spotify client using the .deb package provided [here](https://nightly.link/jpochyla/psst/workflows/build/master) and run apt-get upgrade, the psst spotify client package is "upgraded" to the completely unrelated debian "psst" package, i.e. effectively uninstalled and replaced.

I don't need the other package and I can mark psst the spotify client as hold to solve this. But other people might want to have both of them installed, so I would suggest to rename the debian package to psst-spotify or something similar.

**To Reproduce**
See above.

**Expected behavior**
The two packages co-exist.

**Environment**
 - OS: Linux Mint
 - Version: 21.1

**Additional context**
Should affect all debian-based distros.

**Comment by Insprill** [comment]
I'm not sure what can be done about this, if anyone knows more or has any ideas please share them!

**Comment by cloudybyte** [comment]
I believe the only real solution is to rename the package to either `psst-spotify`, `psst-player` or sth.

**Comment by brianclinkenbeard** [comment]
As a temporary solution, you can use `sudo apt-mark hold psst`. Or, if you don't want to be notified that psst is being held back, you can pin the package by writing the following to `/etc/apt/preferences.d/psst-pin`:
```
Package: psst
Pin: version 1
Pin-Priority: 1001
```

**Comment by ChrisLauinger77** [comment]
I just would name the package:
psst-gui
