### ISSUE TITLE
New liked songs don't appear in saved songs

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#410]
My feeling is that this might be related to loading all the saved songs on startup? Some mechanism might be able to exist to add the songs that were liked in a user's session to the liked songs without any requests (just add to the retrieved stack), every time a user visits their liked page?

**Comment by Insprill** [comment]
Can you elaborate a bit more, and provide steps to reproduce? I'm not exactly sure what the issue is you're describing.

**Comment by jacksongoode** [comment]
Ah yep it is! Didn't see that one!
