### ISSUE TITLE
Cut a release for Flatpak, etc.

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#417]
In order for us to publish to Flathub #141 we need a real semantically versioned release, something that should have been tackled a while ago 😆.

My gut says we just start with `1.0.0` and increment the patch number from there? Maybe it would be good to have an action to do this automatically. @Insprill @TheEvilSkeleton @jpochyla

**Comment by TheEvilSkeleton** [comment]
I agree. Otherwise, if you think it's not production ready, then we could start with experimental releases.

**Comment by Insprill** [comment]
A major version > 0 indicates a stable application, which psst is not. If we switch to semantic versioning, we'll start at `0.1.0`. I haven't used Flatpak before; does it not let us use a git hash for a version? If we are to switch to semantic versioning, I'd like to hear @jpochyla's thoughts.

**Comment by jpochyla** [comment]
Personally I'd prefer `0.1.0`, yes.

**Comment by TheEvilSkeleton** [comment]
> does it not let us use a git hash for a version?

It [the format] does, but Flathub [the store] prefers semantic versioning

**Comment by TheEvilSkeleton** [comment]
You have my approval
