### ISSUE TITLE
Change primary branch from master => main

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#418]
We should change the branch name to the modern standard. There might be some unintended followup consequences with building, etc.

**Comment by jacksongoode** [comment]
@jpochyla Let's go ahead and do it, this is the only repo I work on that has master as head.

**Comment by jpochyla** [comment]
Done @jacksongoode!

**Comment by jacksongoode** [comment]
@jpochyla I think you will need to make `main` the default branch as well. I think a random branch is set to be the default right now.

**Comment by jpochyla** [comment]
@jacksongoode oops, excuse me. Done.
