### ISSUE TITLE
Pasting into search field doesn't work

### ISSUE THREAD

**Issue by shiftgeist** [jpochyla/psst#42]
![image](https://user-images.githubusercontent.com/30648730/110934544-6a4b8300-832e-11eb-8ae0-8ecef41c8fb9.png)

**Comment by jpochyla** [comment]
Copy&paste is implemented through menus now, which are disabled on Linux & Windows. Will get fixed soon!

**Comment by jpochyla** [comment]
Fixed in 0bb5258, Ctrl-X/C/V should work in all inputs on all platforms now.
