### ISSUE TITLE
"Add to queue" in right-click menu

### ISSUE THREAD

**Issue by psharma04** [jpochyla/psst#431]
**Is your feature request related to a problem? Please describe.**
Currently, there is no equivalent of the "add to queue" button on the first party apps.

**Describe the solution you'd like**
When you right-click on a song, it should provide a "play next" or "add to queue" option.

**Describe alternatives you've considered**
N/A

**Additional context**
![in Psst](https://github.com/jpochyla/psst/assets/22587474/2d944576-9f3d-4233-b9dd-91ea7bdd55ed)
![in the MacOS Spotify App](https://github.com/jpochyla/psst/assets/22587474/c6be2974-8db4-4bfd-bdbe-9c0436ac2e2d)

**Comment by SO9010** [comment]
@jacksongoode should we close this now?

**Comment by jacksongoode** [comment]
Haha yeah, thanks for catching this!
