### ISSUE TITLE
No 'package' info found in 'Cargo.toml'

### ISSUE THREAD

**Issue by mitchweaver** [jpochyla/psst#435]
```
mitch@macbook[psst] cargo build --release
...
   Compiling psst-cli v0.1.0 (/tmp/tmp-mitch/psst/psst-cli)k, psst-core, gio, gtk
   Compiling druid v0.8.3 (https://github.com/jpochyla/druid?branch=psst#230f7dd8)
    Finished release [optimized] target(s) in 4m 10sst-gui(bin)
    
mitch@macbook[psst] cargo bundle --release
error: No 'package' info found in 'Cargo.toml'
```

Can't install. Arm64 on Fedora. Runs perfectly fine with cargo run.  
I'm not familiar with Rust or cargo so excuse me if this is a facepalm user error.

**Comment by onpaws** [comment]
What does `cargo check` say?

I'm not an expert but given this repo uses [cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html), I wonder if you might want to `cd` into the `psst-gui ` folder and try again.

**Comment by Insprill** [comment]
You do need to cd into `psst-gui`, that's [what we do in the CI build](https://github.com/jpochyla/psst/blob/67ec1b444112308ef74557225cec3b261a6d724f/.github/workflows/build.yml#L55-L58). If it's still not working this can be reopened.
