### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by toshmukhamedov** [jpochyla/psst#438]
Please consider adding Apple Silicon support to the PSST to optimize performance and energy efficiency for users with Apple Silicon-powered devices. This would enhance the overall user experience and ensure compatibility with Apple's latest hardware architecture.

**Comment by myInstagramAlternative** [comment]
+1

**Comment by Insprill** [comment]
I've created a PR adding an Apple Silicon target to the CI pipeline. You can check it out [here](https://github.com/jpochyla/psst/suites/16808248323/artifacts/959935320), please let me know if it works.

**Comment by onpaws** [comment]
Thanks for the PR @Insprill!

Anecdata in case anyone needs: last month I was able to `cargo build` from `psst-gui/` on an Apple Silicon machine, and it worked, but IIRC it was contingent on running `cargo update` first. 

The CI pipeline will be more convenient for folks and will hopefully get merged. But in case you need to build it directly, it worked as of September 2023 on latest Rust.

**Comment by atoshmukhamedov** [comment]
@Insprill  I also tried this [Psst-aarch64-apple-darwin](https://github.com/jpochyla/psst/suites/16808248323/artifacts/959935320) build and it's still emulated
<img width="959" alt="image" src="https://github.com/jpochyla/psst/assets/79999469/aae9e1ce-4a93-42af-b890-cdb10c799a37">

**Comment by jacksongoode** [comment]
Hmm, for some reason its being cross compiled wrong on  the runners?

**Comment by Insprill** [comment]
Once the latest CI finishes please test again and see if it's fixed.

**Comment by Insprill** [comment]
Can anyone with an M1 and/or Intel mac test the CI build from #450 to confirm that it's working correctly and not being emulated?

**Comment by ralph** [comment]
It works.

<img width="419" alt="Bildschirmfoto 2024-01-22 um 19 52 06" src="https://github.com/jpochyla/psst/assets/2190/eac284bf-ac8e-4e07-bad0-9d244d7fb34a">

<img width="1311" alt="Bildschirmfoto 2024-01-22 um 19 53 08" src="https://github.com/jpochyla/psst/assets/2190/b388d782-4a65-4083-beb9-ed812139699d">

(Downloaded from here: https://github.com/jpochyla/psst/actions/runs/7612693455?pr=450)

**Comment by jacksongoode** [comment]
I think #450 would be good to merge and then we can close this @Insprill

**Comment by jacksongoode** [comment]
Closed with #450
