### ISSUE TITLE
Nightly Link Expired

### ISSUE THREAD

**Issue by secretdenka** [jpochyla/psst#447]
Nightly Link Expired
![image](https://github.com/jpochyla/psst/assets/155559256/f17ac090-3c2a-4415-a618-b843fc442eea)

**Comment by jacksongoode** [comment]
Thank you, progress has stalled a bit and thus no build actions have run in the last 90 days. Hopefully there will be some more development soon :)

**Comment by Insprill** [comment]
I pushed an empty commit to trigger another build
