### ISSUE TITLE
Search inside playlist

### ISSUE THREAD

**Issue by CypherPotato** [jpochyla/psst#456]
**Is your feature request related to a problem? Please describe.**
There should be a way to search for a song or artist within the playlist or saved songs

**Describe the solution you'd like**
A separate search bar, or button that opens the search bar, that when searching, filters the results based on what I searched for. When playing a song from these results, play only the filtered part of the playlist.

**Describe alternatives you've considered**
There is no other way to do this.

**Additional context**
I'm talking about this button.

![image](https://github.com/jpochyla/psst/assets/17441745/f1e6b40a-9121-496f-b70f-4000e519d609)

**Comment by jacksongoode** [comment]
Ohh that's a good idea! Shouldn't be too hard I don't think.

**Comment by CypherPotato** [comment]
@jacksongoode hello. I've tried it in the version from commit #913dae1 but couldn't get it working.

**Comment by jacksongoode** [comment]
@CypherPotato Which platform are you on? The search should really filter the list completely. Right now it just highlights the items that match.

**Comment by SO9010** [comment]
This is addressed in #511; I also found that Cmd/Ctrl+F doesn't work on my devices. The playing from only the filtered part of the playlist doesn't make much sense and could be a very niche use case. However, with the current search filter, it should, as @jacksongoode says, either filter the list by removing the other songs in the playlist or, in my opinion, a far more effective way of doing it would be having an auto-scroll to position a bit like when in VSCode. I am happy to work on this as well.
