### ISSUE TITLE
Preferences window missing title; toolbar clips against macOS window controls

### ISSUE THREAD

**Issue by peterkos** [jpochyla/psst#458]
**Describe the bug**
When "General" tab is selected, the selection background intersects too close to the macOS window controls.

**To Reproduce**
1. Open Preferences for the app
2. Select "General" tab
3. Observe the selection background clipping the "maximize" window button.

**Expected behavior**
1. macOS window controls have a fixed margin around them.

**Screenshots**
<img src="https://github.com/jpochyla/psst/assets/2782749/7397dda4-d2a2-4a4b-bd20-3eeb7959e8b6" width="700px" />

**Environment**
 - OS: macOS Sonoma 14.1
 - Version: 0.1.0

**Comment by jacksongoode** [comment]
This has been fixed with #481
