### ISSUE TITLE
Preferences button almost hidden

### ISSUE THREAD

**Issue by shiftgeist** [jpochyla/psst#46]
![image](https://user-images.githubusercontent.com/30648730/111077300-69fae580-84f0-11eb-8953-e47dc7cbe2d3.png)

When psst-gui is first started, the preferences window is a bit too small in height and not resizable, so the (I guess) apply button is hidden.

Env:
Windows 10 20H2
Psst Version 0bb5258

**Comment by Kethku** [comment]
I think its possible that this is a windows specific bug

**Comment by Kethku** [comment]
I just built and ran under wsl and the issue doesn't occur.

**Comment by jpochyla** [comment]
Uff I'm sorry it took so long, the window sizes in Druid are a bit complicated now :( I'll just increase the height for the Windows build.

**Comment by jpochyla** [comment]
I haven't tested this, in case this still looks wrong, please send screenshots <3

**Comment by Kethku** [comment]
Tested this. Looks correct to me. 
![image](https://user-images.githubusercontent.com/3323631/125842639-f65eb468-6d32-420f-888a-1537e08e1021.png)
