### ISSUE TITLE
Ability to log in via Google account

### ISSUE THREAD

**Issue by OcalaDave** [jpochyla/psst#462]
**Is your feature request related to a problem? Please describe.**
I have a premium Spotify account but log in via my Google account. Thus no username or password.

**Describe the solution you'd like**
Add the ability to log in via Google, Facebook, and Apple, since these are valid Spotify methods.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kingosticks** [comment]
Don't Facebook accounts already work if you setup a device password ? https://www.spotify.com/us/account/set-device-password/

**Comment by OcalaDave** [comment]
Thanks! Didn’t know about that option.
