### ISSUE TITLE
Icon appears garbled in Spotlight results

### ISSUE THREAD

**Issue by BionicBison05** [jpochyla/psst#465]
**Describe the bug**
The app icon appears garbled when searching for Psst with Spotlight

**To Reproduce**
Install the app and search for it with Spotlight

**Expected behavior**
Icon appears normal in Spotlight search

**Screenshots**
<img width="134" alt="Screenshot 2024-04-04 at 5 40 02 PM" src="https://github.com/jpochyla/psst/assets/93722725/da1ccc2f-f95c-4a05-9743-f88a9bd283ac">

**Environment**
 - OS: macOS
 - Version: Sonoma 14.4.1

**Additional context**
N/A

**Comment by jacksongoode** [comment]
I'm not able to reproduce this... Could we get one other person to confirm?

**Comment by BionicBison05** [comment]
So two people I know were also unable to reproduce it, but I can reproduce it in a macOS VM and a second, fresh copy of macOS on my machine, the common denominator being my hardware. Looks like I have some further testing to do on my end. I'll update this when I understand this better, I just don't understand how a hardware(?) issue could only affect one specific app in one specific context.

**Comment by jacksongoode** [comment]
I just now found a case where this happens! I don't think we are treating the macOS icon the right way. I'll investigate.
