### ISSUE TITLE
Cannot find value `TEXT_COLOR` in module `theme`

### ISSUE THREAD

**Issue by Miguel-Alt786** [jpochyla/psst#47]
Hi, i was trying to compile your program (looks awesome btw), but i was getting this weird error, idk nothing about rust so idk if it is something on my machine or on the code, the following is the output of the error

![Screenshot_20210508_003400](https://user-images.githubusercontent.com/69548014/117524738-1a3b1680-af95-11eb-87e1-dac828963147.png)

Thanks.

**Comment by jpochyla** [comment]
Hi! Sorry, should be fixed in the latest commit.
