### ISSUE TITLE
Removes multiple songs if there are duplicates

### ISSUE THREAD

**Issue by SO9010** [jpochyla/psst#477]
**Describe the bug**
When having a song added more than once in a playlist, then you remove one, it removed every single song which is the same. This makes it annoying to then re-add the song, especially if you forget which song this is.

**To Reproduce**
Add a song multiple times to a playlist, then right click onto the song, and then observe all of the songs that are the same disappearing.

**Expected behavior**
Remove just the one song.

**Screenshots**

**Environment**
 - OS: Arch linux

**Comment by jacksongoode** [comment]
This is definitely a bug. We should identify the song key not just by the song itself but also perhaps its position in the playlist.

**Comment by jacksongoode** [comment]
Figured it out. It's actually undocumented but you can remove tracks by index.

https://github.com/JMPerez/spotify-dedup/commit/d0493aa0b760a3e4dd5d747b7cae605fbec60c9c
