### ISSUE TITLE
MacOs version is not universal (doesn't work on Intel Mac on MacOS Ventura)

### ISSUE THREAD

**Issue by alejandrot96** [jpochyla/psst#483]
**Describe the bug**
The app dowloaded from the link on the Readme does not work on intel macs
**To Reproduce**
open the app on an intel mac
**Expected behavior**
get a working mac app
**Screenshots**
<img width="588" alt="image" src="https://github.com/jpochyla/psst/assets/9990374/8a15fb73-81ec-48f3-858c-a395e4835813">

**Environment**
 - OS: MacOS Ventura
 - Version: ? (linked on README)

**Additional context**
I was trying to "update" the app, building from source worked ✌🏽

**Comment by jacksongoode** [comment]
Oh that's not good, maybe something about the way we join the two builds together is bad?

**Comment by jacksongoode** [comment]
@alejandrot96 Can you try this? https://github.com/jpochyla/psst/actions/runs/9686934504/artifacts/1642274979

**Comment by alejandrot96** [comment]
That did not worked 🙁, maybe keep both bundles? (intel & apple silicon)

**Comment by alejandrot96** [comment]
or add a minimum system version when building/bundling?

**Comment by jacksongoode** [comment]
@alejandrot96 https://github.com/jpochyla/psst/actions/runs/9717318336/artifacts/1649774405 Does this one work for you?

**Comment by jacksongoode** [comment]
Fixed in #484 !
