### ISSUE TITLE
Add Fedora Dependency to documentation

### ISSUE THREAD

**Issue by rodhfr** [jpochyla/psst#488]
**Describe the bug**
Additional dependency needed to build with Fedora 40 cubeb-devel available in the fedora repository

**To Reproduce**
Try to build with fresh Fedora 40 installation

**Expected behavior**
Add this to the dependency documentation

**Screenshots**
![image](https://github.com/jpochyla/psst/assets/83579016/9707469f-af5f-4946-b6ea-40135b10ad72)

**Environment**
 - OS: Fedora
 - Version: 40

**Additional context**

**Comment by jacksongoode** [comment]
Just out of curiosity, do you still need this dependency if building from https://github.com/jpochyla/psst/pull/487

**Comment by SO9010** [comment]
I tested it on my laptop running Fedora 40, and it compiles perfectly for me! :P

**Comment by jacksongoode** [comment]
@SO9010 So we can close this or do we need to add that dependency?

**Comment by SO9010** [comment]
@jacksongoode, we can close it. @rodhfr are you sure you have installed all the needed build dependencies, including GTK? I had a similar issue, but installing all dependencies fixed it.
