### ISSUE TITLE
Psst package dependency issue: libssl1.1 deprecated on Ubuntu 22.04

### ISSUE THREAD

**Issue by ProgrammedInsanity** [jpochyla/psst#496]
**Describe the bug**
[Psst requires libssl1.1, which is deprecated and poses a security risk. As a result, it is not installable on Ubuntu 22.04, preventing the .deb package from being installed on this version of the OS.](https://askubuntu.com/a/1412746)
```
(Reading database ... 307382 files and directories currently installed.)
Preparing to unpack psst_1_amd64.deb ...
Unpacking psst-gui (1) over (1) ...
dpkg: dependency problems prevent configuration of psst-gui:
 psst-gui depends on libssl1.1; however:
  Package libssl1.1 is not installed.

dpkg: error processing package psst-gui (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 psst-gui
```

**To Reproduce**
Download the `psst_1_amd64.deb package`.
Attempt to install it on Ubuntu 22.04 using `sudo dpkg -i psst_1_amd64.deb`.

**Expected behavior**
That the package would be installed.

**Potential solution**
migrate to libssl3

**Environment**
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by kingosticks** [comment]
Close this dupe in favour of https://github.com/jpochyla/psst/issues/415
