### ISSUE TITLE
Build errors for arm: armhf and aarch64

### ISSUE THREAD

**Issue by Roet-Ivar** [jpochyla/psst#50]
Hi! I'm not sure if this nice client is meant to be used on arm-devices, in this case L4T-ubuntu on my Switch.
Anyway , when I try building it for **AARCH64 (64 bit)**  using:
`cargo build --release`

error: failed to run custom build command for `ep-miniaudio-sys v2.4.0 (https://github.com/jpochyla/miniaudio-rs#1ff94282)`
 <details> 
  <summary>More</summary>
Caused by:
  process didn't exit successfully: `/home/retropie/Downloads/psst/psst/target/release/build/ep-miniaudio-sys-9346f72f0f4095e6/build-script-build` (exit code: 101)
  --- stdout
  TARGET = Some("aarch64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-unknown-linux-gnu")
  CC_aarch64-unknown-linux-gnu = None
  CC_aarch64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_aarch64-unknown-linux-gnu = None
  CFLAGS_aarch64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None
  CC_aarch64-unknown-linux-gnu = None
  CC_aarch64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_aarch64-unknown-linux-gnu = None
  CFLAGS_aarch64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = None
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-I" "./miniaudio" "-Wall" "-Wextra" "-Wno-unused-function" "-DMINIAUDIO_IMPLEMENTATION=" "-DMA_NO_FLAC=1" "-DMA_NO_MP3=1" "-DMA_NO_WAV=1" "-DMA_LOG_LEVEL=1" "-o" "/home/retropie/Downloads/psst/psst/target/release/build/ep-miniaudio-sys-368fa8058b732cd1/out/./miniaudio-wrapper.o" "-c" "./miniaudio-wrapper.c"
  exit code: 0
  AR_aarch64-unknown-linux-gnu = None
  AR_aarch64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/home/retropie/Downloads/psst/psst/target/release/build/ep-miniaudio-sys-368fa8058b732cd1/out/liblibminiaudio.a" "/home/retropie/Downloads/psst/psst/target/release/build/ep-miniaudio-sys-368fa8058b732cd1/out/./miniaudio-wrapper.o"
  exit code: 0
  running: "ar" "s" "/home/retropie/Downloads/psst/psst/target/release/build/ep-miniaudio-sys-368fa8058b732cd1/out/liblibminiaudio.a"
  exit code: 0
  cargo:rustc-link-lib=static=libminiaudio
  cargo:rustc-link-search=native=/home/retropie/Downloads/psst/psst/target/release/build/ep-miniaudio-sys-368fa8058b732cd1/out
  cargo:rustc-cfg=feature="ma-unix"
  cargo:rustc-cfg=feature="ma-linux"
  cargo:rustc-cfg=feature="ma-posix"
  cargo:rustc-cfg=feature="ma-support-alsa"
  cargo:rustc-cfg=feature="ma-support-pulseaudio"
  cargo:rustc-cfg=feature="ma-support-jack"
  cargo:rustc-cfg=feature="ma-support-null"
  cargo:rustc-cfg=feature="ma-enable-jack"
  cargo:rustc-cfg=feature="ma-enable-alsa"
  cargo:rustc-cfg=feature="ma-enable-pulseaudio"
  cargo:rustc-cfg=feature="ma-enable-null"
  cargo-warning=using pre-generated bindings - these are not guaranteed to always work (!!!)
 
  --- stderr
  thread 'main' panicked at 'bindings for linux-aarch64 do not exist in `bindings/linux-aarch64`, please enable the `bindgen` feature instead', /root/.cargo/git/checkouts/miniaudio-rs-0268a3ab613f78e9/1ff9428/miniaudio-sys/build.rs:60:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
</details>

I gave it a try crosscompiling for **ARMHF (32 bit)** using:
`PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig PKG_CONFIG_ALLOW_CROSS=1 cargo build --target=arm-unknown-linux-gnueabihf --release
`

I receive:
error: failed to run custom build command for `ring v0.16.20`
 
<details> 
  <summary>More</summary>
   Caused by:
  process didn't exit successfully: `/home/retropie/Downloads/psst/psst/target/release/build/ring-1d58efa7e298e7fa/build-script-build` (exit code: 101)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("arm-unknown-linux-gnueabihf")
  HOST = Some("aarch64-unknown-linux-gnu")
  CC_arm-unknown-linux-gnueabihf = None
  CC_arm_unknown_linux_gnueabihf = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_arm-unknown-linux-gnueabihf = None
  CFLAGS_arm_unknown_linux_gnueabihf = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None
 
  --- stderr
  running "arm-linux-gnueabihf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv6" "-marm" "-mfpu=vfp" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/retropie/Downloads/psst/psst/target/arm-unknown-linux-gnueabihf/release/build/ring-e6ba255990d1bed0/out/aesv8-armx-linux32.o" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux32.S"
  thread 'main' panicked at 'failed to execute ["arm-linux-gnueabihf-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv6" "-marm" "-mfpu=vfp" "-I" "include" "-Wall" "-Wextra" "-pedantic" "-pedantic-errors" "-Wall" "-Wextra" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-fno-strict-aliasing" "-fvisibility=hidden" "-fstack-protector" "-g3" "-DNDEBUG" "-c" "-o/home/retropie/Downloads/psst/psst/target/arm-unknown-linux-gnueabihf/release/build/ring-e6ba255990d1bed0/out/aesv8-armx-linux32.o" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/pregenerated/aesv8-armx-linux32.S"]: No such file or directory (os error 2)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:653:9
</details>

I think this client looks beautiful and I'd love to have it up running, but I totally understand if it's not supported.
Thanks!

**Comment by jpochyla** [comment]
I don't have any HW with these architectures, plus this is all upstream stuff, sorry. Pull requests are welcome, of course.

**Comment by TheOnAndOnlyZenomat** [comment]
I got around this fix by adding "bindgen" to the features list for miniaudio in `psst-core/Cargo.toml` and installing clang

**Comment by Roet-Ivar** [comment]
> I got around this by adding "bindgen" to the features list for miniaudio in `psst-core/Cargo.toml` and installing clang

Awesome I'll give it a try! <3
Since I'm not very familiar with cargo build system, would this change be useful as a pull request or does it break other architectures?

**Comment by TheOnAndOnlyZenomat** [comment]
Sorry, I can't really help out with the pango stuff, I use Manjaro. What is the exact error apt fails with?
I am not sure if that would work, but we could try, tho I could only send you the binary and related files in a few hours.
I could imagine, that this wont work tho, because I think it is dynamically linked...

**Comment by jpochyla** [comment]
We don't use miniaudio anymore, closing.
