### ISSUE TITLE
Credits support

### ISSUE THREAD

**Issue by LuckyTheCoder** [jpochyla/psst#509]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When right clicking on a track (playing or not), you'll have to option to view credits of a song.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jacksongoode** [comment]
Definitely would want to see this! We would need some third party API to get this info since Spotify does not provide the credits as an endpoint.

**Comment by jacksongoode** [comment]
It would be a great first PR if you'd like to @LuckyTheCoder, my guess either MusicBrainz or Discogs could be integrated as both have free APIs. And then we would just need a button to trigger the action in a new window!

**Comment by kingosticks** [comment]
I believe track credits can be obtained from `GET https://spclient.wg.spotify.com/track-credits-view/v0/experimental/<TRACK>/credits` with valid Bearer authorization and client-token headers, You'll get a JSON response.

**Comment by LuckyTheCoder** [comment]
> It would be a great first PR if you'd like to @LuckyTheCoder, my guess either MusicBrainz or Discogs could be integrated as both have free APIs. And then we would just need a button to trigger the action in a new window!

Contrary to popular belief, I am not much of a coder (at least as of now)!

**Comment by jacksongoode** [comment]
I'm close to finishing up a PR if you wanna check it out #526

**Comment by Pogodaanton** [comment]
#526 has been merged. Can we close this?

**Comment by jacksongoode** [comment]
Yep! Thanks!
