### ISSUE TITLE
Linux GUI title bar is not dark in dark mode on Gnome

### ISSUE THREAD

**Issue by emilia-miki** [jpochyla/psst#510]
**Describe the bug**
On linux with GNOME as the DE, putting system appearance in dark mode and psst into dark mode in settings still keeps the title bar light.

**To Reproduce**
Install psst on linux with GNOME, use dark mode both in GNOME and psst.

**Expected behavior**
I expect the title bar to be dark, like the rest of the UI.

**Screenshots**
![image](https://github.com/user-attachments/assets/8ecbfc24-3182-4e0c-9ea1-c15d57e78ecf)

**Environment**
 - OS: NixOS on Apple Silicon, GNOME Shell 46.3.1
 - Version: commit 6c9cd3f91653764b832ea5136cda04c9e0f8fe50

**Additional context**
https://github.com/jpochyla/druid seems to be discontinued now, ideally it should be replaced with something that's more maintained. I didn't investigate druid much yet, maybe it uses an older version of GTK which is not configured properly on my machine. I haven't written any code in Rust since some uni projects, but if I have the time I'll try to get more info.

**Comment by emilia-miki** [comment]
solved by setting environment variable GTK_THEME=Adwaita:dark

**Comment by jacksongoode** [comment]
Right, druid could be replaced, however the amount of work would be quite a lot and it would be nice to at least get this project into a confident bug-less state first. Is there something we can do to fix this so you don't have to set it yourself?

**Comment by emilia-miki** [comment]
> Right, druid could be replaced, however the amount of work would be quite a lot and it would be nice to at least get this project into a confident bug-less state first. Is there something we can do to fix this so you don't have to set it yourself?

Apparently you can't, because it's controlled by the window manager. Unless you're willing to draw a fully custom titlebar with https://docs.gtk.org/gtk3/class.HeaderBar.html

The problem is that GTK4 works correctly with both Adwaita-dark and Adwaita:dark as the theme name, but GTK3 accepts only Adwaita:dark, and my system by default used Adwaita-dark. Maybe you could add this to some FAQ or a warning log, but not much more.
