### ISSUE TITLE
Authentication Failure on login

### ISSUE THREAD

**Issue by Magiks21** [jpochyla/psst#523]
**Describe the bug**
Using the same username and password I have always used to log into Spotify Premium I am met with "Authentication Failed: bad credentials" I am using a fresh install on a Raspberry Pi 5. I am running the latest/stable build 04c6261 off of the Ubuntu App Center. Let me know if I can provide any further detail

**To Reproduce**
Log into psst

**Expected behavior**
Log into use psst

**Screenshots**

**Environment**
 - OS: Ubuntu
 - Version: 24.04.1 LTS arm64

**Additional context**

**Comment by jacksongoode** [comment]
You should update to the recent build where we do Oauth logins, Spotify has depreciated user/pass logins.
