### ISSUE TITLE
400 error when saving track

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#527]
@SO9010 Are you getting this issue? I think it might have to do with the recent PR.

**Comment by SO9010** [comment]
Yes I am actually I only get it on the first attempt to save it any other time after it works

**Comment by SO9010** [comment]
Wow, that was a massive oversight; when changing the get put, etc., functions, I set them all to get!

**Comment by RensOliemans** [comment]
I get a 400 error code when removing a track from a current playlist. Is this related, or should I create a new issue?

**Comment by SO9010** [comment]
Hello,

This should be solved now 🙂
________________________________
