### ISSUE TITLE
Incorrect font

### ISSUE THREAD

**Issue by winteriscariot** [jpochyla/psst#552]
I'm not sure why, but Psst is displaying a monospace font for most of the content:

![image](https://github.com/user-attachments/assets/c7b7ac4f-5cea-400a-9fdc-0db7b3a3b4fc)

What is the font that the application should be using, so I can ensure it's installed correctly?

**Comment by jacksongoode** [comment]
What platform are you on?

**Comment by winteriscariot** [comment]
Arch Linux, psst-git r561.0292319-1

i'm pretty sure it's a fontconfig issue on my end, i just wanted to see if i could figure out which font it's *supposed* to be then work from there.

**Comment by winteriscariot** [comment]
it was indeed a fontconfig issue and i took some drastic changes that revealed my local config issue. thank you, closed.

**Comment by jacksongoode** [comment]
Thanks for figuring it out!
