### ISSUE TITLE
Wrong padding in home section

### ISSUE THREAD

**Issue by jacksongoode** [jpochyla/psst#556]
**Describe the bug**

Uniquely yours doesn't have the proper padding beneath it?

<img width="230" alt="image" src="https://github.com/user-attachments/assets/33762e73-c211-415f-b36c-f7695011d7ec">

While other sections do:

<img width="196" alt="image" src="https://github.com/user-attachments/assets/22d68968-83ed-454d-92a3-059ed4e3a546">

@SO9010 I think you might have some better sense of why this is since you led that PR.

**Comment by SO9010** [comment]
Ah, I think this is an easy fix! Submitting a pr now!
