### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by omartijn** [jpochyla/psst#559]
**Describe the bug**
Since at least today search is broken and yields a "Failed to read JSON: invalid type: null, expected struct Album at line 1 column 29237". The message is identical, with the exception of the column.

**To Reproduce**
Open psst, enter text in the search field and press enter.

**Expected behavior**
Psst should display search results

**Screenshots**

**Environment**
 - OS: Linux
 - Version: 69314f9fe8e86d57a678ab333b08ab3ffcf2a3bb

**Additional context**
I think something changed in the JSON for search results, breaking psst.

**Comment by SO9010** [comment]
Hello, Is this still an issue for you?

**Comment by omartijn** [comment]
Nope, it seems to work fine again.

**Comment by SO9010** [comment]
Perfect thank you!
