### ISSUE TITLE
Undefined Symbol Error

### ISSUE THREAD

**Issue by shiftgeist** [jpochyla/psst#58]
The error I get when I start `psst-gui`:

```
psst-gui: symbol lookup error: psst-gui: undefined symbol: pango_attr_insert_hyphens_new
```

I'm on Debian 10. Installed psst via the `.deb` package provides in the actions (from commit `0161cc1`).

**Comment by jpochyla** [comment]
This looks like an issue on Druid part, possibly it depends on a newer version of Pango?

**Comment by shiftgeist** [comment]
@jpochyla I have no experience with Druid or Pango. If you tell me how I can help further debugging this, I'd gladly do so. Last commit I tried where this accures is `11cec9d`.

**Comment by jpochyla** [comment]
This is likely caused by the system `pango` being older than required by Druid. Not much we can do about this.
