### ISSUE TITLE
Remember volume from previous session

### ISSUE THREAD

**Issue by fkaa** [jpochyla/psst#60]
Right now Psst always starts at 100% volume for me, would be nice if it somehow remembered the volume set from previous sessions.

**Comment by pythonhacker** [comment]
Suggest adding this to ~/.config/Psst in Linux. I saw it contains the auth data and audio-quality and theme settings as of now.

**Comment by jpochyla** [comment]
Implemented in 6484d242a99b4d1c7431e40d5a3300471ba37905 🎧
