### ISSUE TITLE
Resizing sends the controls off the screen

### ISSUE THREAD

**Issue by Kethku** [jpochyla/psst#72]
![image](https://user-images.githubusercontent.com/3323631/125852083-e94b59fe-cf45-40d3-96a8-fb532791fde4.png)
I think this should be changed to set a minimum size for the window such that the controls are always visible and or dynamically hide/restructure the controls bar so that the name of the song is on top of the play pause seek controls

**Comment by jpochyla** [comment]
I've increased the minimal window size in master and made some improvements to the playback layout (controls are now centered if there's enough space, otherwise align to the right). In the future we might switch to the vertical layout as you suggest, if the horiz. space is small.

**Comment by jpochyla** [comment]
I'll close this, as the controls are now contained properly. We can improve on the layout later in another issue.
