### ISSUE TITLE
Ctrl-A doesn't select in the text box

### ISSUE THREAD

**Issue by Kethku** [jpochyla/psst#73]
Specifically the search box doesn't respond to ctrl+a for selecting the whole textbox. This could be a windows specific thing?

**Comment by Kethku** [comment]
https://github.com/linebender/druid/issues/1854 looks like upstream issue

**Comment by Kethku** [comment]
Its very possible this is windows specific

**Comment by jpochyla** [comment]
This happens on Mac as well, yes I think it's a Druid issue, I'll look into it.

**Comment by dbrgn** [comment]
Same thing happens on Linux (e.g. in the settings, in the username/password fields).

**Comment by jpochyla** [comment]
Somewhat fixed in upstream (it works, modulo some missing invalidation I think). Closing! <3
