### ISSUE TITLE
can't run release on macos 

### ISSUE THREAD

**Issue by matthiasdebernardini** [jpochyla/psst#8]
matthiasdebernardini@Matthiass-MacBook-Pro ~/g/psst (master) [101]> cargo build --release
    Updating git repository `https://github.com/jpochyla/miniaudio-rs`
error: failed to get `miniaudio` as a dependency of package `psst-core v0.1.0 (/Users/matthiasdebernardini/gits/psst/psst-core)`

Caused by:
  failed to load source for dependency `miniaudio`

Caused by:
  Unable to update https://github.com/jpochyla/miniaudio-rs#1ff94282

Caused by:
  failed to fetch into /Users/matthiasdebernardini/.cargo/git/db/miniaudio-rs-0268a3ab613f78e9

Caused by:
  http parser error: stream ended at an unexpected time; class=Http (34)

Thats the error I got, any tips? this looks really nice btw.

**Comment by matthiasdebernardini** [comment]
same with dev and `cargo run`

**Comment by fixmk** [comment]
For me it works. Tried it right now.
Make sure you don't have any network / connection issues

**Comment by matthiasdebernardini** [comment]
its not a network issue, the response can't get parsed. 

Are you on big sur?

**Comment by keeslinp** [comment]
Works for me. I'm on Catalina

**Comment by matthiasdebernardini** [comment]
hmm maybe its a big sur thing

**Comment by jasikpark** [comment]
https://github.com/rust-lang/cargo/issues/6513 -- maybe this is helpful? 

I am running macOS 11.1 Big Sur and have had no problems building release.

**Comment by matthiasdebernardini** [comment]
I updated cargo with `rustup update stable` and it fixed the issue.
