### ISSUE TITLE
Use cargo bundle

### ISSUE THREAD

**Issue by Kethku** [jpochyla/psst#82]
This would enable icons to be added to the built assets for linux and macos

**Comment by Kethku** [comment]
https://github.com/jpochyla/psst/issues/74

**Comment by Kethku** [comment]
An example for how this could be done can be found here in the pipeline here: https://github.com/Kethku/neovide/blob/main/.github/workflows/build.yml#L109
and in the configuration here:
https://github.com/Kethku/neovide/blob/main/Cargo.toml#L70

**Comment by jpochyla** [comment]
Thanks for the pointers! I have it ready, got stuck on designing the icon :)

**Comment by jpochyla** [comment]
Minimal bundle info added in b10c34ff53a8d93cb44b4dc6eddb75874c7246c8, more incoming.

**Comment by jpochyla** [comment]
There's now a rudimentary `cargo bundle` integration in CI (for macOS).
