### ISSUE TITLE
Limit framerate 

### ISSUE THREAD

**Issue by Heychsea** [jpochyla/psst#86]
On Windows 10 (TBC elsewhere), scrolling "furiously" makes my GPU go a little wild (like 60% usage). A classic scrolling makes my GPU go up to 20%, which is still manageable but a little high in my opinion. Including a hard 60 fps (or same as display) limit would further limit resource consumption.

**Comment by Qrbaker** [comment]
That may be an upstream bug with the UI toolkit, druid: https://github.com/linebender/druid

**Comment by jpochyla** [comment]
Hi, I'm tagging this as enhancement. The performance goals I'm trying to target is the lowest possible CPU/GPU usage while idling and playing, and 100% responsiveness on user interaction.

**Comment by Heychsea** [comment]
I investigated a bit more. I don't have the issue on macOS, and the issue on Windows was fixed indirectly by enabling vsync at the os level (Nvidia control panel). I couldn't really find a way to control that with druid, I'll look into it a bit more later.

**Comment by jacksongoode** [comment]
Is this still an issue? I'll close if not.

**Comment by jacksongoode** [comment]
You were running on Windows? Do you remember any other conditions?

**Comment by jacksongoode** [comment]
I've tested this on a very similar setup on Windows with no excessive CPU/GPU.
