### ISSUE TITLE
Addition of keyboard controls 

### ISSUE THREAD

**Issue by geowal19** [jpochyla/psst#91]
On Mac OS hiding with CMD+H and playing/pausing with space bar etc...

**Comment by jpochyla** [comment]
Definitely in the queue!

**Comment by JuliDi** [comment]
Do you have any other suggestions for keyboard controls/shortcuts?

As noted in the PR, I've managed to add CMD+H to hide the application and ctrl+space to pause/resume the song. However, I could not get it to react to a single keystroke (i.e. without a modifier like ctrl or cmd). If there's a solution to that, I could add some more shortcuts.

**Comment by jpochyla** [comment]
I'd like to get complete keyboard navigation working, i.e. keyboard focus for some clickable main-content links. This should probably come with a redesigned search component (and that would need a lot of thinking, first).
