### ISSUE TITLE
Documentation: Dependencies/versions unclear

### ISSUE THREAD

**Issue by winks** [jpochyla/psst#95]
Tried to build this on Ubuntu 18.04 today.

> Requested 'pango >= 1.44' but version of Pango is 1.40.14

I suggest you put the distro version you tested on in the README. (Because I'm not sure it would work on 20.04? Debian buster?)

Also this was after I had to run `rustup update stable` because there also wasn't a known good version given, this might be similar to #88.

**Comment by jpochyla** [comment]
I've mentioned that latest stable Rust is required, thanks! I'd take PRs for the Linux dependencies, as I develop and test only on macOS.

**Comment by mannykoum** [comment]
I am using the latest stable rust on Ubuntu 18.04 (1.55.0) and getting the same issue

> Requested 'pango >= 1.44' but version of Pango is 1.40.14

**Comment by kaenovsky** [comment]
I'm getting this same error on Debian 10 Buster. `rustup update` won't solve it. Does anyone know any other approach?
