### ISSUE TITLE
Fedora build dependencies

### ISSUE THREAD

**Issue by svelle** [jpochyla/psst#98]
Hey just wanted to leave this here for anyone who's building on Fedora (34)

Here's most if not all of the dependencies needed to build psst.

`sudo dnf install dbus-devel rust-glib-sys-devel rust-cairo-rs-devel rust-pango-devel rust-atk-devel rust-gdk-pixbuf-devel cairo-gobject-devel rust-gdk-devel`

Feel free to close this one out if you don't want issues like this open.

Thanks for all the work and cheers!

**Comment by lslavkov** [comment]
Wish I could build psst on F32. I will wait once I receive new laptop and fresh install.

**Comment by brownjohnf** [comment]
Would you consider opening a PR adding this to the readme, or adding a github action to do CI builds on fedora?

**Comment by svelle** [comment]
Sure. I'll look into that.

**Comment by jpochyla** [comment]
Hi @svelle! I've merged 0fd1f92 with some RHEL/Fedora dependencies, if they are not sufficient (maybe `gtk3-devel` covers the rest from your attempts?), please open a PR <3
